<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Ordenes de Compra</h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaOrdenesDeCompra" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Fecha de Liberación</th>
                            <th class="text-center">Solicitante</th>
                            <th class="text-center">Nodo</th>
                            <th class="text-center">Ejecutor</th>
                            <th class="text-center">Planifica Tarea</th>
                        </tr>
                    </thead>
                    <tbody id="bodyOrdenesDeCompra">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrOrdenesDeCompraJSON = <?= $arrOrdenesDeCompraJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaOrdenesDeCompra();
    });

    function dibujarTablaOrdenesDeCompra(){
        $('#bodyOrdenesDeCompra').find('tr').remove();
    
        for (var i = 0; i < arrOrdenesDeCompraJSON.length; i++)
        {
            var ordenDeCompra = arrOrdenesDeCompraJSON[i];

            var body = document.getElementById("bodyOrdenesDeCompra");
            var row = body.insertRow();
            row.id = i;

            var fecha = row.insertCell(0);
            var solicitante = row.insertCell(1);
            var nodo = row.insertCell(2);
            var ejecutor = row.insertCell(3);
            var planificaTarea = row.insertCell(4);

            fecha.innerHTML = ordenDeCompra.fechaLiberacion;
            solicitante.innerHTML = ordenDeCompra.solicitante.nombre + ', ' + ordenDeCompra.solicitante.apellido;
            nodo.innerHTML = ordenDeCompra.nodo.nombre;
            ejecutor.innerHTML = ordenDeCompra.ejecutor.nombre + ', ' + ordenDeCompra.ejecutor.apellido;
            planificaTarea.innerHTML = ordenDeCompra.planificaTarea.nombre + ', ' + ordenDeCompra.planificaTarea.apellido;
        }
    }

    $(function() {
        $('#tablaOrdenesDeCompra').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarTarea() {
        var result = null;
        var ordenDeCompra = arrOrdenesDeCompraJSON[filaSeleccionada];

        $.ajax({
            url: url + '/ordenes-de-compra/borrar/' + ordenDeCompra.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var ordenDeCompra = arrOrdenesDeCompraJSON[filaSeleccionada];
            
            swal({
                title: 'Eliminar Tarea',
                width: 600,
                text: "Esta seguro que desea eliminar la orden de compra: "+ ordenDeCompra.resumen +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Confirmar'
            }).then((result) => {
                if (result.value) {
                    borrarTarea();
                    window.location.replace(url + "/ordenes-de-compra");
                }
            });
        }else{
            swal('Tarea no seleccionado',
                'Por favor seleccione el orden de compra que desea eliminar',
                'error');
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var ordenDeCompra = arrOrdenesDeCompraJSON[filaSeleccionada];

            window.location.replace(url + "/ordenes-de-compra/editar/" + ordenDeCompra.id);
        }else{
            swal('Tarea no seleccionado',
                'Por favor seleccione la orden de compra que desea editar',
                'error');
        }
    }

  </script>