<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Ordenes_de_Compra__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaOrdenesDeCompra" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Fecha_de_Liberacion__') ?></th>
                            <th class="text-center"><?= $this->translate('__Solicitante__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nodo__') ?></th>
                            <th class="text-center"><?= $this->translate('__Ejecutor__') ?></th>
                            <th class="text-center"><?= $this->translate('__Planifica_Tarea__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyOrdenesDeCompra">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrTareasJSON = <?= $arrTareasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaOrdenesDeCompra();
    });

    function dibujarTablaOrdenesDeCompra(){
        $('#bodyOrdenesDeCompra').find('tr').remove();
    
        for (var i = 0; i < arrTareasJSON.length; i++)
        {
            var tarea = arrTareasJSON[i];

            var body = document.getElementById("bodyOrdenesDeCompra");
            var row = body.insertRow();
            row.id = i;

            var fecha = row.insertCell(0);
            var solicitante = row.insertCell(1);
            var nodo = row.insertCell(2);
            var ejecutor = row.insertCell(3);
            var planificaTarea = row.insertCell(4);

            fecha.innerHTML = tarea.ordenDeCompra.fechaLiberacion;
            solicitante.innerHTML = tarea.solicitante.nombre + ', ' + tarea.solicitante.apellido;
            nodo.innerHTML = tarea.nodo.nombre;
            ejecutor.innerHTML = tarea.ejecutor.nombre + ', ' + tarea.ejecutor.apellido;
            planificaTarea.innerHTML = tarea.planificaTarea.nombre + ', ' + tarea.planificaTarea.apellido;
        }
    }

    $(function() {
        $('#tablaOrdenesDeCompra').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarTarea() {
        var result = null;
        var tarea = arrTareasJSON[filaSeleccionada];

        $.ajax({
            url: url + '/ordenes-de-compra/borrar/' + tarea.ordenDeCompra.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var tarea = arrTareasJSON[filaSeleccionada];
            
            swal({
                title: '<?= $this->translate('__Eliminar_Tarea__') ?>',
                width: 600,
                text: "<?= $this->translate('__preg_confirmar_eliminar_ord_de_compra__') ?>: "+ tarea.ordenDeCompra.descripcion +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarTarea();
                    window.location.replace(url + "/ordenes-de-compra");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var tarea = arrTareasJSON[filaSeleccionada];

            window.location.replace(url + "/ordenes-de-compra/editar/" + tarea.ordenDeCompra.id);
        }
    }

  </script>