<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Nuevo_Usuario__') ?></h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formUsuario" name="formUsuario">
                    <div class="form-row mt-5">
                        <div class="col-lg-6">
                            <div class="form-row">
                                <div class="col-md-4">
                                    <label for="userName"><span class="obligatorio">(*) </span><?= $this->translate('__nombre_de_usuario__') ?>:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="userName" name="userName" class="form-control" required="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-10 alert alert-danger" id="divErrorNombreUsuario" style="display:none;">
                                    <?= $this->translate('__mensaje_nombre_usuario_duplicado__') ?>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="contraseniaUsuario"><span class="obligatorio">(*) </span><?= $this->translate('__Contraseña__') ?>:</label>
                                </div>
                                <div class="col-md-7">
                                    <input type="password" id="contraseniaUsuario" name="contraseniaUsuario" class="form-control" required="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="nombreUsuario"><span class="obligatorio">(*) </span><?= $this->translate('__Nombre__') ?>:</label>
                                </div>
                                <div class="col-md-7">
                                    <input type="text" id="nombreUsuario" name="nombreUsuario" class="form-control" required="true">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-row">
                                <div class="col-md-2">
                                    <label for="emailUsuario"><span class="obligatorio">(*) </span>Email:</label>
                                </div>
                                <div class="col-md-9">
                                    <input type="text" id="emailUsuario" name="emailUsuario" class="form-control" required="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-4">
                                    <label for="contraseniaRepetida"><span class="obligatorio">(*) </span><?= $this->translate('__Repetir_Contraseña__') ?>:</label>
                                </div>
                                <div class="col-md-7">
                                    <input type="password" id="contraseniaRepetida" name="contraseniaRepetida" class="form-control" required="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="apellidoUsuario"><span class="obligatorio">(*) </span><?= $this->translate('__Apellido__') ?>:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="apellidoUsuario" name="apellidoUsuario" class="form-control" required="true">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-row mt-5">
                        <div class="col-md-1">
                            <label for="idPerfil"><?= $this->translate('__Perfil__') ?>:</label>
                        </div>  
                        <div class="col-md-4">
                            <select id="idPerfil" name="idPerfil" class="form-control">
                                <option value="-1">-- <?= $this->translate('__Seleccione__') ?> --</option>
                                <?php foreach($arrPerfiles as $Perfil) :?>
                                    <option value="<?= $Perfil->getId() ?>"><?= $Perfil->getNombre() ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <div class="btn btn-primary" onclick="agregarPerfil();"><?= $this->translate('__Agregar__') ?></div>
                        </div>
                    </div>
                    <div class="form-row mt-5">
                        <table class="table table-hover" data-page-size="15">
                            <thead>
                                <tr>
                                    <th><?= $this->translate('__Perfiles_Asociados__') ?></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="bodyPerfiles">

                            </tbody>
                        </table>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var usuariosJson = <?= $UsuariosJson ?>;
var arrPerfiles = [];
var nombreUsuarioValido = '<?= $nombreUsuarioValido ?>';

function FormUsuarioToJson(){
    var formData = {
        username: $('#userName').val(), 
        clave: $('#contraseniaUsuario').val(), 
        nombre: $('#nombreUsuario').val(),
        apellido: $('#apellidoUsuario').val(),
        email: $('#emailUsuario').val(),
        perfiles: arrPerfiles
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function controlarContrasenias(){
    var contrasenia = $('#contraseniaUsuario').val();
    var contraseniaRepetida = $('#contraseniaRepetida').val();

    return (contrasenia == contraseniaRepetida);
}

function preSubmit(){
    var contraseniasIguales = controlarContrasenias();

    if (!contraseniasIguales){
        swal('<?= $this->translate('__Error_en_las_contraseñas__') ?>',
            '<?= $this->translate('__mensaje_contraseñas_incorrectas__') ?>',
            'error');
        return;
    }

    var JsonData = FormUsuarioToJson();
    $('#JsonData').val(JsonData);

    if ($("#formUsuario")[0].checkValidity()){
        $("#formUsuario").submit();
    }else{
        $("#formUsuario")[0].reportValidity();
    }
}

$( document ).ready(function() {
    if (usuariosJson !== ''){
        $('#userName').val(usuariosJson.userName);
        $('#nombreUsuario').val(usuariosJson.nombre);
        $('#apellidoUsuario').val(usuariosJson.apellido);
        $('#emailUsuario').val(usuariosJson.email);

        arrPerfiles = usuariosJson.perfiles;
        actualizarPerfiles();
    }
    
    $('#userName').change(function (){
        var nombreUsuarioValido = getNombreUsuarioEsValido(this.value);
        
        if (!nombreUsuarioValido){
            $('#divErrorNombreUsuario').show(500);
        }else{
            $('#divErrorNombreUsuario').hide(500);
        }
    });

    verificarMostrarBotonGuardar();
});

function agregarPerfil(){
    var combo = document.getElementById("idPerfil");
    
    var IdPerfilSeleccionado = combo.value;
    var NombrePerfilSeleccionado =  combo.options[combo.selectedIndex].text;
    
    if(IdPerfilSeleccionado > 0){
        if(!existePerfil(IdPerfilSeleccionado)){
            addPerfil(IdPerfilSeleccionado,NombrePerfilSeleccionado);
        }
        else{
            swal(
                '<?= $this->translate('__Perfil_duplicado__') ?>!',
                '<?= $this->translate('__mensaje_perfil_duplicado__') ?>',
                'error'
            );
        }
    }
    else{
        swal(
            '<?= $this->translate('__Perfil_No_Seleccionado__') ?>!',
            '<?= $this->translate('__Seleccione_un_perfil__') ?>',
            'error'
        );  
    }
    actualizarPerfiles();
}

function addPerfil(IdPerfilSeleccionado, NombrePerfilSeleccionado){    
    
    var nuevoPerfil = {
        'id': IdPerfilSeleccionado,
        'nombre' : NombrePerfilSeleccionado
    };
    
    arrPerfiles.push(nuevoPerfil);
}

function agregarBotonBorrarPerfil(contenedor, idPerfil, nombrePerfil){
    var icon = document.createElement('i');
    icon.setAttribute('class','fa p16 fa-trash-alt');

    var div = document.createElement('div');
    div.setAttribute('class','btn btn-danger btn-circle btn-outline');
    div.setAttribute('onclick', 'borrarPerfil(' + idPerfil + ', \'' + nombrePerfil + '\')');

    div.appendChild(icon);

    contenedor.appendChild(div);
}

function actualizarPerfiles(){
   $('#bodyPerfiles').find('tr').remove();

    for (var i = 0; i < arrPerfiles.length; i++)
    {
        var perfil = arrPerfiles[i];

        var body = document.getElementById("bodyPerfiles");
        var row = body.insertRow();

        var nombre = row.insertCell(0);
        var borrar = row.insertCell(1);

        nombre.innerHTML = perfil.nombre;
        agregarBotonBorrarPerfil(borrar, perfil.id, perfil.nombre);
    }
}

function borrarPerfil(IdPerfil, nombre){
    swal({
        title: '<?= $this->translate('__Eliminar_Usuario__') ?>',
        width: 600,
        text: "<?= $this->translate('__mensaje_eliminar_perfil__') ?>: " + nombre + "?",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
        confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
    }).then((result) => {
        if (result.value) {
            eliminarPerfil(IdPerfil);
            swal(
                '<?= $this->translate('__Eliminado__') ?>!',
                '<?= $this->translate('__El_perfil_ha_sido_eliminado__') ?>',
                'success'
            )
        }
    })  
};

function eliminarPerfil(IdPerfil){
    arrPerfiles.forEach(function(datosFila){
        if (datosFila.id == IdPerfil){
            pos = arrPerfiles.indexOf(datosFila);
            arrPerfiles.splice(pos, 1);
        }
    });
    actualizarPerfiles();
}

function existePerfil(IdPerfil){
    var existe = false;
    arrPerfiles.forEach(function(datosFila){
        if (datosFila.id == IdPerfil){
            existe = true;
        }
    });
    return existe;
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

function getNombreUsuarioEsValido(nombreUsuario) {
    var result = null;
    
    $.ajax({
        url: url + '/configuracion/usuarios/nombreusuariovalido/' + nombreUsuario,
        type: 'get',
        dataType: 'json',
        async: false,
        success: function (data) {
            result = data.esValido;
        }
    });
    
    return result;
}

</script>