<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("configuracion/usuarios",["action" => "alta"])?>">Nuevo Usuario</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Usuarios</h3>
            </div>
            <div class="panel-body">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre de Usuario</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Email</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrUsuarios as $Usuario) : ?>
                        <tr>
                            <td><?= $Usuario->getNombreUsuario() ?></td>
                            <td><?= $Usuario->getNombre() ?></td>
                            <td><?= $Usuario->getApellido() ?></td>
                            <td><?= $Usuario->getEmail() ?></td>
                            <td>
                                <a href="<?=$this->url("configuracion/usuarios",
                                                    ["action" => "editar", "id" => $Usuario->getId()])?>">editar</a> | 
                                <a href="<?=$this->url("configuracion/usuarios",
                                                    ["action" => "borrar", "id" => $Usuario->getId()])?>">borrar</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>