<div class="form-row">
    <div class="col-md-2 offset-10">
        <a href="<?=$this->url("abm/entidad",["entidad" => "operacion", "action" => "alta"])?>" class="btn btn-primary">Nueva Operación</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Operaciones</h3>
            </div>
            <div class="panel-body">
                <table class="footable table table-stripped toggle-arrow-tiny no-borders">
                    <thead>
                        <tr>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Titulo</th>
                            <th class="text-center">Icono</th>
                            <th class="text-center">Grupo</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrEntidades as $Operacion) : ?>
                        <tr>
                            <td><?= $Operacion->getNombre() ?></td>
                            <td><?= $Operacion->getTitulo() ?></td>
                            <td><?= $Operacion->getIcono() ?></td>
                            <td><?= ($Operacion->getGrupo()) ? $Operacion->getGrupo()->getTitulo() : '' ?></td>
                            <td class="form-row">
                                <div class="col-md-5">
                                    <a href="<?=$this->url("abm/entidad",
                                        ["entidad" => "operacion", "action" => "editar", "id" => $Operacion->getId()]
                                        )?>" class="btn btn-success">Editar</a>
                                </div>
                                <div class="col-md-5 offset-2">
                                    <a href="<?=$this->url("abm/entidad",
                                        ["entidad" => "operacion", "action" => "borrar", "id" => $Operacion->getId()]
                                        )?>" class="btn btn-danger">Borrar</a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="flex">
                    <a href="<?=$this->url("abm",["action" => "listar"])?>" class="btn btn-primary">Volver</a>
                </div>
            </div>
        </div>
    </div>

</div>