<?php

namespace DoctrineORMModule\Proxy\__CG__\DBAL\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuarios extends \DBAL\Entity\Usuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'NombreUsuario', 'Clave', 'Bloqueado', 'FechaAlta', 'Email', 'Nombre', 'Apellido', 'AceptaTerminosUso', 'Perfiles'];
        }

        return ['__isInitialized__', 'id', 'NombreUsuario', 'Clave', 'Bloqueado', 'FechaAlta', 'Email', 'Nombre', 'Apellido', 'AceptaTerminosUso', 'Perfiles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNombreUsuario($NombreUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreUsuario', [$NombreUsuario]);

        return parent::setNombreUsuario($NombreUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setClave($Clave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClave', [$Clave]);

        return parent::setClave($Clave);
    }

    /**
     * {@inheritDoc}
     */
    public function setBloqueado($Bloqueado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBloqueado', [$Bloqueado]);

        return parent::setBloqueado($Bloqueado);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($FechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$FechaAlta]);

        return parent::setFechaAlta($FechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($Email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$Email]);

        return parent::setEmail($Email);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoUsuario($TipoUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoUsuario', [$TipoUsuario]);

        return parent::setTipoUsuario($TipoUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($Nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$Nombre]);

        return parent::setNombre($Nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function setApellido($Apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellido', [$Apellido]);

        return parent::setApellido($Apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function setAceptaTerminosUso($AceptaTerminosUso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAceptaTerminosUso', [$AceptaTerminosUso]);

        return parent::setAceptaTerminosUso($AceptaTerminosUso);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreUsuario', []);

        return parent::getNombreUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClave', []);

        return parent::getClave();
    }

    /**
     * {@inheritDoc}
     */
    public function getBloqueado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBloqueado', []);

        return parent::getBloqueado();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoUsuario', []);

        return parent::getTipoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellido', []);

        return parent::getApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function getAceptaTerminosUso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAceptaTerminosUso', []);

        return parent::getAceptaTerminosUso();
    }

    /**
     * {@inheritDoc}
     */
    public function getJSON()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJSON', []);

        return parent::getJSON();
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfiles', []);

        return parent::getPerfiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addPerfil(\DBAL\Entity\Perfiles $perfil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerfil', [$perfil]);

        return parent::addPerfil($perfil);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllPerfiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllPerfiles', []);

        return parent::removeAllPerfiles();
    }

}
