<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Nueva_Pregunta__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <form method="post" name="formPregunta" id="formPregunta">
                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="preguntaNombre"><span class="obligatorio">(*) </span><?= $this->translate('__Descripcion__') ?>:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="preguntaNombre" name="preguntaNombre" class="form-control" required="true">
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">                 
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var preguntaesJson = <?= $PreguntasJson ?>;

function FormPreguntasToJson(){
    var formData = {
        descripcion: $('#preguntaDescripcion').val(),
        valor: $('#preguntaValor').val(),
        nombre: $('#preguntaNombre').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormPreguntasToJson();
    $('#JsonData').val(JsonData);

    if ($("#formPregunta")[0].checkValidity()){
        $("#formPregunta").submit();
    }else{
        $("#formPregunta")[0].reportValidity();
    }
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

$( document ).ready(function() {
    if (preguntaesJson !== ''){
        $('#preguntaDescripcion').val(preguntaesJson.descripcion);
    }

    verificarMostrarBotonGuardar();
});
</script>