<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nuevo Perfil</h3>
            </div>
            <div class="panel-body mt-5">
                <form method="post" name="formPerfil" onsubmit="preSubmit()">
                    <div class="form-row">
                        <div class="col-md-3">
                            <label for="perfilNombre"><span class="obligatorio">(*) </span>Nombre:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="perfilNombre" name="perfilNombre" class="form-control" required="true">
                        </div>
                    </div>
                    <div class="form-row mt-3">
                        <div class="col-md-3">
                            <label for="perfilDescripcion"><span class="obligatorio">(*) </span>Descripción:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="perfilDescripcion" name="perfilDescripcion" class="form-control" required="true">
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">                        
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var perfilesJson = <?= $PerfilesJson ?>;

function FormPerfilesToJson(){
    var formData = {
        descripcion: $('#perfilDescripcion').val(),
        nombre: $('#perfilNombre').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormPerfilesToJson();
    $('#JsonData').val(JsonData);

    if ($("#formPerfil")[0].checkValidity()){
        $("#formPerfil").submit();
    }else{
        $("#formPerfil")[0].reportValidity();
    }
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

$( document ).ready(function() {
    if (perfilesJson !== ''){
        $('#perfilDescripcion').val(perfilesJson.descripcion);
        $('#perfilNombre').val(perfilesJson.nombre);
    }

    verificarMostrarBotonGuardar();
});
</script>