<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Perfiles__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaPerfiles" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Nombre__') ?></th>
                            <th class="text-center"><?= $this->translate('__Descripcion__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyConfPerfiles">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrPerfilesJSON = <?= $arrPerfilesJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaPerfiles();
    });

    function dibujarTablaPerfiles(){
        $('#bodyConfPerfiles').find('tr').remove();
    
        for (var i = 0; i < arrPerfilesJSON.length; i++)
        {
            var perfil = arrPerfilesJSON[i];

            var body = document.getElementById("bodyConfPerfiles");
            var row = body.insertRow();
            row.id = i;

            var nombre = row.insertCell(0);
            var descripcion = row.insertCell(1);

            nombre.innerHTML = perfil.nombre;
            descripcion.innerHTML = perfil.descripcion;   
        }
    }

    $(function() {
        $('#tablaPerfiles').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarPerfil() {
        var result = null;
        var perfil = arrPerfilesJSON[filaSeleccionada];

        $.ajax({
            url: url + '/configuracion/perfiles/borrar/' + perfil.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var perfil = arrPerfilesJSON[filaSeleccionada];
            
            swal({
                title: 'Eliminar Perfil',
                width: 600,
                text: "Esta seguro que desea eliminar el perfil: "+ perfil.descripcion +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Confirmar'
            }).then((result) => {
                if (result.value) {
                    borrarPerfil();
                    window.location.replace(url + "/configuracion/perfiles");
                }
            });
        }else{
            swal('Perfil no seleccionado',
                'Por favor seleccione el perfil que desea eliminar',
                'error');
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var perfil = arrPerfilesJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/perfiles/editar/" + perfil.id);
        }else{
            swal('Perfil no seleccionado',
                'Por favor seleccione el perfil que desea editar',
                'error');
        }
    }

  </script>