<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('font-awesome/css/all.css'))
            ->appendStylesheet($this->basePath('css/sweetalert.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
            ->appendFile($this->basePath('js/sweetalert2.all.js'))
        ?>
    </head>
    <body>
        
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <div class="form-row">

                <?php foreach ($arrAccionesDisponibles as $accionesDisponibles) :?>
                    <div class="col-md-3">
                        <?php if ($accionesDisponibles->getUrlDestino()) :?>
                            <a href="<?=$this->url($accionesDisponibles->getUrlDestino(),
                                                    ["action" => $accionesDisponibles->getControllerAction()])?>">
                                <i class="<?= $accionesDisponibles->getAccion()->getIcono() ?>"></i><?= $accionesDisponibles->getAccion()->getTitulo() ?>
                            </a>
                        <?php else: ?>
                            <button class="btn" onclick="<?= $accionesDisponibles->getJsFunction() ?>">
                                <?= $accionesDisponibles->getAccion()->getTitulo() ?>
                            </button>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
                </div>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
<script>
    var url = '<?= $this->serverUrl(); ?>';
</script>
