<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <?php if ($arrAccionesDisponibles) :?>
                <div class="row">
                    <a href="<?=$this->url($arrAccionesDisponibles[0]->getUrlDestino(),
                                            ["action" => $arrAccionesDisponibles[0]->getControllerAction()])?>">
                        <?= $arrAccionesDisponibles[0]->getAccion()->getTitulo() ?>
                    </a>
                </div>
                <?php endif; ?>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
