<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Operaciones</h3>
            </div>
            <div class="panel-body">
                <table id="tablaOperaciones" class="footable table table-stripped toggle-arrow-tiny no-borders">
                    <thead>
                        <tr>
                            <th class="text-center">Nombre</th>
                            <th class="text-center">Titulo</th>
                            <th class="text-center">Icono</th>
                            <th class="text-center">Grupo</th>
                        </tr>
                    </thead>
                    <tbody id="bodyOperaciones">
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script>
    var filaSeleccionada = -1;
    var arrOperacionesJSON = <?= $arrOperacionesJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaOperaciones();
    });

    function dibujarTablaOperaciones(){
        $('#bodyOperaciones').find('tr').remove();
    
        for (var i = 0; i < arrOperacionesJSON.length; i++)
        {
            var operacion = arrOperacionesJSON[i];

            var body = document.getElementById("bodyOperaciones");
            var row = body.insertRow();
            row.id = i;

            var nombre = row.insertCell(0);
            var titulo = row.insertCell(1);
            var icono = row.insertCell(2);
            var grupo = row.insertCell(3);

            nombre.innerHTML = operacion.nombre;
            titulo.innerHTML = operacion.titulo;
            icono.innerHTML = operacion.icono;
            
            if (operacion.grupo.hasOwnProperty('titulo')){
                grupo.innerHTML = operacion.grupo.titulo;
            }else{
                grupo.innerHTML = ' - ';
            }
            
        }
    }

    $(function() {
        $('#tablaOperaciones').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarOperacion() {
        var result = null;
        var operacion = arrOperacionesJSON[filaSeleccionada];

        $.ajax({
            url: url + '/abm/operacion/borrar/' + operacion.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
               
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var operacion = arrOperacionesJSON[filaSeleccionada];
            
            swal({
                title: 'Eliminar Operación',
                width: 600,
                text: "Está seguro que desea eliminar la operación: "+ operacion.nombre +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarOperacion();
                    window.location.replace(url + "/abm/operacion");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var operacion = arrOperacionesJSON[filaSeleccionada];

            window.location.replace(url + "/abm/operacion/editar/" + operacion.id);
        }
    }

  </script>