<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nueva Relación Operación - Accion - Perfil</h3>
            </div>
            <div class="panel-body">
                <form method="post" name="formAltaOperacionAccionPerfil" onsubmit="preSubmit()">
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="idOperacion"><span class="obligatorio">(*) </span>Operación:</label>
                        </div>
                        <div class="col-md-4">
                            <select id="idOperacion" name="idOperacion" class="form-control" required="true">
                                <option value="">-- Seleccione --</option>
                                <?php foreach($arrVariables['Operaciones'] as $Operacion) :?>
                                    <option value="<?= $Operacion->getId() ?>"><?= $Operacion->getTitulo() ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="idAccion"><span class="obligatorio">(*) </span>Acción:</label>
                        </div>
                        <div class="col-md-4">
                            <select id="idAccion" name="idAccion" class="form-control" required="true">
                                <option value="">-- Seleccione --</option>
                                <?php foreach($arrVariables['Acciones'] as $Accion) :?>
                                    <option value="<?= $Accion->getId() ?>"><?= $Accion->getTitulo() ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="idPerfil"><span class="obligatorio">(*) </span>Perfil:</label>
                        </div>
                        <div class="col-md-4">
                            <select id="idPerfil" name="idPerfil" class="form-control" required="true">
                                <option value="">-- Seleccione --</option>
                                <?php foreach($arrVariables['Perfiles'] as $Perfil) :?>
                                    <option value="<?= $Perfil->getId() ?>"><?= $Perfil->getNombre() ?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="urlDestino">URL Destino:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="urlDestino" name="urlDestino" class="form-control"
                            value="<?= ($Entidad) ? $Entidad->getUrlDestino() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="jsFunction">Función JS:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="jsFunction" name="jsFunction" class="form-control"
                            value="<?= ($Entidad) ? $Entidad->getJsFunction() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="idHTMLElement">Id Elemento HTML:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="idHTMLElement" name="idHTMLElement" class="form-control"
                            value="<?= ($Entidad) ? $Entidad->getIdHTMLElement() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="ordenUbicacion"><span class="obligatorio">(*) </span>Ubicación en footer:</label>
                        </div>
                        <div class="col-md-2">
                            <select id="ordenUbicacion" name="ordenUbicacion" class="form-control" required="true">
                                <option value="">-- Seleccione --</option>
                                <?php for ($i = 1; $i <= 12; $i++) :?>
                                    <option value="<?= $i ?>"><?= $i ?></option>
                                <?php endfor;?>
                            </select>
                        </div>
                    </div>
                    <div class="row form-group">
                        <input type="hidden" name="JsonData" id="JsonData">
                        <a href="<?=$this->url("abm/operacionAccionPerfil", ["action" => "index"])?>" class="btn btn-secondary">Cancelar</a>
                        <button type="submit" class="btn btn-primary ml-3">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
function FormAltaOperacionAccionPerfilToJson(){
    var formData = {
        idOperacion: $('#idOperacion').val(), 
        idAccion: $('#idAccion').val(), 
        idPerfil: $('#idPerfil').val(),
        urlDestino: $('#urlDestino').val(),
        ordenUbicacion: $('#ordenUbicacion').val(),
        jsFunction: $('#jsFunction').val(),
        idHTMLElement: $('#idHTMLElement').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormAltaOperacionAccionPerfilToJson();
    $('#JsonData').val(JsonData);

    if ($("#formAltaOperacionAccionPerfil")[0].checkValidity()){
        $("#formAltaOperacionAccionPerfil").submit();
    }else{
        $("#formAltaOperacionAccionPerfil")[0].reportValidity();
    }
}
</script>