<script>
$(document).ready(function(){

      $("#content").removeClass("content");
   
});
</script>
<div class="row center-xs ">
    <div class="col-xs-12 col-md-4 login">
        <form class="form-signin" method="post">

            <!-- <div class="alert alert-warning" role="alert">
                Incorrect login and/or password. 
                <a href="">Forgot password?</a>
            </div> -->

            <img id="profile-img" class="profile-img-card" src="img/login/soup.png" />
            <div style="margin-bottom:15px;"></div>
            <label>Nombre de Usuario: <input type="text"></label>
            <label>Clave: <input type="password"></label>
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Remember me
                </label>
            </div>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
    </div>
</div>