<script>
$(document).ready(function(){

      $("#content").removeClass("content");
   
});
</script>
<div class="form-row center-xs ">
    <div class="col-xs-12 col-md-10 login">
        <div class="form-row align-items-center">
            <div class="col-lg-4 offset-1">
                <div class="text-center">
                    <!-- <img id="profile-img" src="img/Coca-Cola_Femsa_Logo.png" /> -->
                    <img id="profile-img" src=<?= $logo_empresa?> />
                </div>
            </div>
            <div class="col-lg-5 offset-1 mx-auto">
                <form class="form-signin" method="post">
                    <!-- <div class="alert alert-warning" role="alert">
                        Incorrect login and/or password. 
                        <a href="">Forgot password?</a>
                    </div> -->
                    <div class="form-row mt-3">
                        <div class="col-lg-5 text-left">
                            <label><?= $this->translate('__nombre_de_usuario__') ?>:</label>
                        </div>
                        <div class="col-lg-7">
                            <input type="text" class="form-control" name="Usuario">
                        </div>
                    </div>
                    <div class="form-row mt-3">
                        <div class="col-lg-3 text-left">
                            <label><?= $this->translate('__Clave__') ?>:</label>
                        </div>
                        <div class="col-lg-9">
                            <input type="password" class="form-control" name="Clave">
                        </div>
                    </div>
                    <div class="form-row mt-3">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> <?= $this->translate('__Recordarme__') ?>
                            </label>
                        </div>
                    </div>
                    <div class="form-row mt-3">
                        <button class="btn btn-lg btn-primary btn-block" type="submit"><?= $this->translate('__Ingresar__') ?></button>
                    </div>
                </form>
            </div>
        </div>
        <div class="">
        </div>
        <div class=""></div>
        
    </div>
</div>