<div class="form-row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Listado de Entidades en el Sistema</h3>
                </div>
                <div class="panel-body">
                    <table id="tablaAcciones" class="footable table table-stripped toggle-arrow-tiny no-borders">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Titulo</th>
                                <th class="text-center">Icono</th>
                            </tr>
                        </thead>
                        <tbody id="bodyAcciones">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    

</script>