<script type="text/javascript" src="<?= $this->basePath('/js/operation/permits/forms/jquery.multi-select.js') ?>"></script>
<script>
    var formulario = <?= $formulario ?>;

    function createListFromJSONLista(selector, lista, seleccione) {
        if (seleccione){
            var option = document.createElement("option");
            option.value =  -1;
            option.text = 'Seleccione';
            selector.appendChild(option);
        }
        
        for (var i=0; i < lista.length; i++) {
            var option = document.createElement("option");
            option.value = lista[i];
            option.text = lista[i];
            selector.appendChild(option);
        }
        return selector;
    }

    function obtenerListaOpciones(lista){
        var output = [];
        for (var i=0; i < lista.length; i++) {
            var item = lista[i];
            output.push(item.descripcion);
        }
        return output;
    }

    function createSimpleSelector(opciones, divElement) {
        
        var selector = document.createElement("select");
        var opciones = obtenerListaOpciones(opciones);
        var selector = createListFromJSONLista(selector, opciones, true);
        divElement.appendChild(selector);
    }

    function createMultipleSelector(id, name, opciones, divElement, size) {
        var selector = document.createElement("select");
        selector.name = name;
        selector.id = id;
        selector.multiple = true;
        selector.size = size;
        var opciones = obtenerListaOpciones(opciones);
        var selector = createListFromJSONLista(selector, opciones, false);
        divElement.appendChild(selector);
    }

    function createDivClass(info, div) {
        var divClass = document.createElement("Div");
        divClass.className = info;
        divClass.style.paddingTop = "15px";
        div.appendChild(divClass);
        return divClass;
    }

    function createButton(id, title, divElement, icon){
        var button = document.createElement("button");
        button.type = "button";
        button.id = id;
        button.title = title;
        button.className = "btn btn-primary";
        button.textContent = icon;
        // var icono = document.createElement("i");
        // icono.className = "fas fa-angle-left";
        // button.appendChild(icono);
        divElement.appendChild(button);
    }

    function deleteOptions(origin) {
        var select1 = document.getElementById(origin);
        var notSelected = [];
        for (var i = 0; i < select1.length; i++) {
            if (!select1.options[i].selected) notSelected.push(select1.options[i].value);
        }
        createListFromJSONLista(selectIn, notSelected, false);
    }

    function insertarElementInSelect(origin, destination){
        var select1 = document.getElementById(origin);
        var selected1 = [];
        for (var i = 0; i < select1.length; i++) {
            if (select1.options[i].selected) selected1.push(select1.options[i].value);
        }
        var optionOrigin = deleteOptions(origin);
        var selectIn = document.getElementById(destination);
        createListFromJSONLista(selectIn, selected1, false);
    }

    $(function() {$("#Positive_rightSelected").click(function() {
        insertarElementInSelect("MultiSelectDisp", "Positive_to"); });
    });
        
    $(function() {$("#Negative_rightSelected").click(function() {
        insertarElementInSelect("MultiSelectDisp", "Negative_to");});
    });

    $(function() {$("#Positive_leftSelected").click(function(){
        insertarElementInSelect("Positive_to", "MultiSelectDisp");});
    });
        
    $(function() {$("#Negative_leftSelected").click(function(){
        insertarElementInSelect("Negative_to", "MultiSelectDisp");});
    });

    function createMultipleSelectorSkeleton(opciones, opciones_in, opciones_out, divElement){
        var divForm = createDivClass("form-row", divElement);

        var div_class_lg_3 = createDivClass("col-lg-3", divForm);
        createMultipleSelector('MultiSelectDisp', 'MultiSelectDisp', opciones, div_class_lg_3, 10);

        var div_class_lg_1 = createDivClass("col-lg-1", divForm);
        createButton("Positive_rightSelected", "Añadir seleccionados", div_class_lg_1, ">");
        createButton("Positive_leftSelected", "Quitar seleccionados", div_class_lg_1, "<");
        createButton("Negative_rightSelected", "Añadir seleccionados", div_class_lg_1, ">");
        createButton("Negative_leftSelected", "Quitar seleccionados", div_class_lg_1, "<");

        var div_class_lg_3_2 = createDivClass("col-lg-3", divForm);
        createMultipleSelector('Positive_to', 'Positive_to', opciones_in, div_class_lg_3_2, 5);
        createMultipleSelector('Negative_to', 'Negative_to', opciones_out, div_class_lg_3_2, 5);
    }

    function createInput(divElement){
        ele = document.createElement('input');
        ele.type = 'text';
        ele.name = 'respuesta'.i;
        divElement.appendChild(ele);
    } 

    function createOptions(item, divElement){
        if(item.tipoPregunta.descripcion == 'simple'){
            var opciones = item.opciones;
            createSimpleSelector(opciones, divElement);
        } else if(item.tipoPregunta.destinos == 1) {
            var opciones = item.opciones;
            createMultipleSelectorSkeleton(opciones, [],[], divElement);
        } else {
            //luego
        }
    }
    
    function createAnswer(item, divElement){
        if (item.cerrada == '1'){
            createOptions(item, divElement);
        } else {
            createInput(divElement);
        }
    }

    function createQuestions(item, divElement){
        preguntas = item.preguntas;
        for (var i = 0; i < preguntas.length; i++){
            var item = preguntas[i];
            var pregunta = document.createElement("P");
            var text = document.createTextNode(item.descripcion);
            pregunta.appendChild(text);
            divElement.appendChild(pregunta);
            createAnswer(item, divElement);
        }
    }

    function crearItemSeccion(item, contenedor){

        // Creating a div element
        var divElement = document.createElement("Div");
        divElement.id = "secciones";

        // Styling it
        divElement.style.textAlign = "lefth";
        // divElement.style.fontWeight = "bold";
        // divElement.style.fontSize = "smaller";
        divElement.style.paddingTop = "15px";

        // Adding a paragraph to it
        var paragraph = document.createElement("P");
        var text = document.createTextNode(item.nombre);
        paragraph.appendChild(text);
        divElement.appendChild(paragraph);

        createQuestions(item, divElement);

        // Appending the div element to body
        contenedor.appendChild(divElement);
            
        return divElement;
    }

    function construirSecciones(childs, contenedor){
        var paragraph = document.createElement("P");
        var text = document.createTextNode(formulario.descripcion);
        paragraph.appendChild(text);
        contenedor.appendChild(paragraph);

        for (var i = 0; i < childs.length; i++){
            var item = childs[i];

            var itemSeccion = crearItemSeccion(item, contenedor);
            contenedor.appendChild(itemSeccion);
        }
    }

    function crearFormulario(){
        construirSecciones(formulario.secciones, document.getElementsByTagName("div")[0]);
    }

    crearFormulario();
</script>

