<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Configuración</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <a href="<?=$this->url("configuracion/tipo-pregunta",["action" => "index"])?>">Tipo Pregunta</a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("configuracion/perfiles",["action" => "index"])?>">Perfiles</a>
                </div>
            </div>
        </div>
    </div>
</div>