<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__configuracion__') ?></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <a href="<?=$this->url("configuracion/tipo-pregunta",["action" => "index"])?>"><?= $this->translate('__tipo_pregunta__') ?></a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("configuracion/perfiles",["action" => "index"])?>"><?= $this->translate('__perfiles__') ?></a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("configuracion/usuarios",["action" => "index"])?>"><?= $this->translate('__usuarios__') ?></a>
                </div>
            </div>
        </div>
    </div>
</div>