<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Configuración</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <a href="">Tipo Pregunta</a>
                </div>
                <div class="row">
                    <a href="">Tipo Sección</a>
                </div>
            </div>
        </div>
    </div>
</div>