<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de ABM</h3>
            </div>
            <div class="panel-body">
                <div class="flex">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "accion", "action" => "listar"])?>" class="btn btn-outline-primary">Acciones</a>
                </div>
                <div class="flex mt-3">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "operacion", "action" => "listar"])?>" class="btn btn-outline-primary">Operaciones</a>
                </div>
                <div class="flex mt-3">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "operacionAccionPerfil", "action" => "listar"])?>" class="btn btn-outline-primary">Acciones - Operaciones Por Perfil</a>
                </div>
            </div>
        </div>
    </div>

</div>