<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Parametros__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaParametros" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Parametro__') ?></th>
                            <th class="text-center"><?= $this->translate('__Valor__') ?></th>
                            <th class="text-center"><?= $this->translate('__Descripcion__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyConfParametros">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrParametrosJSON = <?= $arrParametrosJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaParametros();
    });

    function dibujarTablaParametros(){
        $('#bodyConfParametros').find('tr').remove();
    
        for (var i = 0; i < arrParametrosJSON.length; i++)
        {
            var parametro = arrParametrosJSON[i];

            var body = document.getElementById("bodyConfParametros");
            var row = body.insertRow();
            row.id = i;

            var nombre = row.insertCell(0);
            var valor = row.insertCell(1);
            var descripcion = row.insertCell(2);

            nombre.innerHTML = parametro.nombre;
            valor.innerHTML = parametro.valor;
            descripcion.innerHTML = parametro.descripcion;   
        }
    }

    $(function() {
        $('#tablaParametros').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarPerfil() {
        var result = null;
        var parametro = arrParametrosJSON[filaSeleccionada];

        $.ajax({
            url: url + '/configuracion/parametros/borrar/' + parametro.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var parametro = arrParametrosJSON[filaSeleccionada];
            
            swal({
                title: '<?= $this->translate('__Eliminar_Parametro__') ?>',
                width: 600,
                text: "<?= $this->translate('__mensaje_eliminar_parametro__') ?>: "+ parametro.descripcion +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarPerfil();
                    window.location.replace(url + "/configuracion/parametros");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var parametro = arrParametrosJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/parametros/editar/" + parametro.id);
        }
    }

  </script>