<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Nueva_Tarea__') ?></h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formTarea" name="formTarea">
                    <div class="form-row mt-5">
                        <div class="col-lg-8 offset-2">
                            <div class="form-row">
                                <div class="col-md-2">
                                    <label for="nodoTarea"><span class="obligatorio">(*) </span><?= $this->translate('__Nodo__') ?>:</label>
                                </div>
                                <div class="col-md-9">
                                    <select id="nodoTarea" name="nodoTarea" class="form-control" required="true">
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-2">
                                    <label for="formularioTarea"><span class="obligatorio">(*) </span><?= $this->translate('__Formulario__') ?>:</label>
                                </div>
                                <div class="col-md-9">
                                    <select id="formularioTarea" name="formularioTarea" class="form-control" required="true">
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-2">
                                    <label for="resumenTarea"><span class="obligatorio">(*) </span><?= $this->translate('__Resumen__') ?>:</label>
                                </div>
                                <div class="col-md-9">
                                    <input type="text" id="resumenTarea" name="resumenTarea" class="form-control" required="true" maxlenght="125">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-2">
                                    <label for="descripcionTarea"><span class="obligatorio">(*) </span><?= $this->translate('__Descripcion__') ?>:</label>
                                </div>
                                <div class="col-md-9">
                                    <textarea id="descripcionTarea" name="descripcionTarea" class="form-control" required="true" rows="7" maxlength="1000"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var tareasJson = <?= $TareasJson ?>;
var arrNodosJSON = <?= $arrNodosJSON ?>;
var arrFormularioJSON = <?= $arrFormularioJSON ?>;

function FormTareaToJson(){
    var iPosNodo = $('#nodoTarea').val();
    var iPosFormulario = $('#formularioTarea').val();
    
    var formData = {
        nodo: arrNodosJSON[iPosNodo],
        formulario: arrFormularioJSON[iPosFormulario], 
        resumen: $('#resumenTarea').val(), 
        descripcion: $('#descripcionTarea').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormTareaToJson();
    $('#JsonData').val(JsonData);

    if ($("#formTarea")[0].checkValidity()){
        $("#formTarea").submit();
    }else{
        $("#formTarea")[0].reportValidity();
    }
}

$( document ).ready(function() {
    dibujarSelectNodos();
    dibujarSelectFormulario();

    if (tareasJson !== ''){
        $('#resumenTarea').val(tareasJson.resumen);
        $('#descripcionTarea').val(tareasJson.descripcion);
        seleccionarNodo();
        seleccionarFormulario();
    }
    
    verificarMostrarBotonGuardar();
});

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

function seleccionarNodo(){
    for (var i = 0; i < arrNodosJSON.length; i++){
        var nodo = arrNodosJSON[i];

        if (nodo.id == tareasJson.nodo.id){
            $('#nodoTarea').val(i);
            break;
        }
    }
}

function seleccionarFormulario(){
    for (var i = 0; i < arrFormularioJSON.length; i++){
        var formulario = arrFormularioJSON[i];

        if (formulario.idFormulario == tareasJson.relevamiento.formulario.idFormulario){
            $('#formularioTarea').val(i);
            break;
        }
    }
}

function dibujarSelectNodos(){
    $('#nodoTarea')
        .find('option')
        .remove();

    $('#nodoTarea')
        .append($("<option></option>")
            .attr("value", -1)
            .text('-- Seleccione --'));

    for (var i = 0; i < arrNodosJSON.length; i++){
        var nodo = arrNodosJSON[i];

        var option = $("<option></option>")
                            .attr("value", i)
                            .text(nodo.nombre);

        $('#nodoTarea').append(option);
    }
}

function dibujarSelectFormulario(){
    $('#formularioTarea')
        .find('option')
        .remove();

    $('#formularioTarea')
        .append($("<option></option>")
            .attr("value", -1)
            .text('-- Seleccione --'));

    for (var i = 0; i < arrFormularioJSON.length; i++){
        var formulario = arrFormularioJSON[i];

        var option = $("<option></option>")
                            .attr("value", i)
                            .text(formulario.nombre);

        $('#formularioTarea').append(option);
    }
}

</script>