<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Asignar_operarios_a_la_Planificacion__') ?></h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formPlanificacion" name="formPlanificacion">
                    <div class="form-row mt-5">
                        <div class="col-lg-5">
                            <div class="form-row">
                                <div class="col-md-5">
                                    <label for="nroOrdenDeCompra"><?= $this->translate('__Orden_de_Compra__') ?> Nº:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="nroOrdenDeCompra" name="nroOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-5">
                                    <label for="fechaLiberacion"><?= $this->translate('__Fecha_de_Liberacion__') ?>:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="fechaLiberacion" name="fechaLiberacion" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="solicitanteOrdenDeCompra"><?= $this->translate('__Solicitante__') ?>:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="solicitanteOrdenDeCompra" name="solicitanteOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="ejecutorOrdenDeCompra"><?= $this->translate('__Ejecutor__') ?>:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="ejecutorOrdenDeCompra" name="ejecutorOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="descripcionOrdenDeCompra"><?= $this->translate('__Descripcion__') ?>:</label>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-11">
                                    <textarea id="descripcionOrdenDeCompra" name="descripcionOrdenDeCompra" class="form-control" readonly="true" rows="12" maxlength="1000"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="form-row">
                                <div class="card" id="divPlanificacion">
                                    <div class="card-header">
                                        <?= $this->translate('__Detalles_de_la_Planificacion__') ?>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-row">
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="fechaInicio"><?= $this->translate('__Fecha_Inicio__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="date" id="fechaInicio" name="fechaInicio" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="fechaFin"><?= $this->translate('__Fecha_Fin__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="date" id="fechaFin" name="fechaFin" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="horaInicio"><?= $this->translate('__Hora_Inicio__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="text" id="horaInicio" name="horaInicio" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="horaFin"><?= $this->translate('__Hora_Fin__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="text" id="horaFin" name="horaFin" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-2">
                                                <label for="titulo"><?= $this->translate('__Titulo__') ?>:</label>
                                            </div>
                                            <div class="col-md-10">
                                                <input type="text" id="titulo" name="titulo" class="form-control" readonly="true">
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-3">
                                                <label for="observaciones"><?= $this->translate('__Observaciones__') ?>:</label>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-12">
                                                <textarea name="observaciones" id="observaciones" class="form-control" readonly="true"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row col-md-3 mt-2">
                                    <label for="formularioPlanificacion">
                                        <?= $this->translate('__operarios__') ?>:</label>
                            </div>
                            <div class="form-row mt-2">
                                <div class="form-group col-md-1"> </div>
                                <div class="form-group col-md-5">
                                    <select name="operariosPlanificacion_1" id="operariosPlanificacion_1" 
                                    class="form-control" multiple></select>
                                </div>
                                <div class="form-group col-md-1">
                                    <button type="button" id="boton_1" class="btn btn-primary" 
                                    title="Añadir seleccionados"
                                    onclick='insertarElementInSelect("operariosPlanificacion_1", "operariosPlanificacion_2")'>></button>
                                    
                                    <button type="button" id="boton_2" class="btn btn-primary mt-2" 
                                    title="Quitar seleccionados"
                                    onclick='insertarElementInSelect("operariosPlanificacion_2", "operariosPlanificacion_1")'><</button>
                                </div>
                                <div class="form-group col-md-5">
                                    <select name="operariosPlanificacion_2" id="operariosPlanificacion_2" 
                                    class="form-control" multiple></select>                                
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
var PlanificacionJSON = <?= $PlanificacionJSON ?>;
var TareaJSON = <?= $TareaJSON ?>;
var arrOperariosJSON = <?= $arrOperariosJSON ?>;


function obtenerElementosSelector(idSelector){
    var select1 = document.getElementById(idSelector);
    var options = [];
    for (var i = 0; i < select1.length; i++) {
            var formData = {
                id :  select1.options[i].value
                };
            options.push(formData);
    }

    return options ;
}

function FormPlanificacionToJson(){
    var formData = {
        operariosSeleccionadas :  obtenerElementosSelector("operariosPlanificacion_2"),
        operariosNoSeleccionadas : obtenerElementosSelector("operariosPlanificacion_1"),
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function mostrarCartelErrorSubmit() { //ver que texto poner
        swal({
            type: 'error',
            title: '<?= $this->translate('__falta_responder_pregunta_operarios__') ?>',
        })
    }

function preSubmit(){
    var JsonData = FormPlanificacionToJson();
    $('#JsonData').val(JsonData);

    if($("#operariosPlanificacion_2 option").length == 0) {
        mostrarCartelErrorSubmit();
    } else {
        swal({
        title: '<?= $this->translate('__Usted_esta_seguro__') ?>',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
        confirmButtonText: '<?= $this->translate('__Si__') ?>',
        }).then((result) => {
        if (result.value) {
            $("#formPlanificacion").submit();
        }
        })
    }
}

$( document ).ready(function() {
    dibujarDatosOrdenDeCompra();
    dibujarSelectFormulario();
    dibujarDetallePlanificacion();
    
    verificarMostrarBotonGuardar();
    manageButtons();
});

function manageButtons(){
    if($("#operariosPlanificacion_1 option").length == 0){
        $("#boton_1").prop('disabled', true);
    } else {
        $("#boton_1").prop('disabled', false);
    }
    if($("#operariosPlanificacion_2 option").length == 0){
        $("#boton_2").prop('disabled', true);
    } else {
        $("#boton_2").prop('disabled', false);
    }
}

function createListFromJSONLista(selector, lista) {     
    for (var i=0; i < lista.length; i++) {
        var option = document.createElement("option");
        item = lista[i];
        option.value = item[0]; //id
        option.text = item[1]; //descripcion
        option.title = item[1];
        selector.appendChild(option);
    }
    return selector;
}

function removeAllOptionSelector(origin){
        $('#'+origin).find('option')
            .remove()
            .end();
    }

function deleteOptionsSelectorOrigen(origin) {
    var selectOrigen = document.getElementById(origin);
    var notSelected = [];
    for (var i = 0; i < selectOrigen.length; i++) {
        if (!selectOrigen.options[i].selected) {
            var array = [];
            array.push(selectOrigen.options[i].value);
            array.push(selectOrigen.options[i].text);
            notSelected.push(array);
        }
    }
    removeAllOptionSelector(origin);
    createListFromJSONLista(selectOrigen, notSelected);
}

function obtenerElementosSeleccionados(idSelectorOrigen){
    var select1 = document.getElementById(idSelectorOrigen);
    var options = [];
    for (var i = 0; i < select1.length; i++) {
        if (select1.options[i].selected) {
            var array = [];
            array.push(select1.options[i].value);
            array.push(select1.options[i].text);
            options.push(array);
        }
    }
    return options;
}

function insertarElementInSelect(idSelectorOrigen, idSelectDestino){

    var options = obtenerElementosSeleccionados(idSelectorOrigen);
    deleteOptionsSelectorOrigen(idSelectorOrigen);

    var selectIn = document.getElementById(idSelectDestino);
    
    createListFromJSONLista(selectIn, options);
    manageButtons();

}

function deleteOptionsSelectorOrigen(origin) {
    var selectOrigen = document.getElementById(origin);
    var notSelected = [];
    for (var i = 0; i < selectOrigen.length; i++) {
        if (!selectOrigen.options[i].selected) {
            var array = [];
            array.push(selectOrigen.options[i].value);
            array.push(selectOrigen.options[i].text);
            notSelected.push(array);
        }
    }
    removeAllOptionSelector(origin);
    createListFromJSONLista(selectOrigen, notSelected);
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

function transformarFechaParaInput(fecha){
    var arrFecha = fecha.split('-');

    if (arrFecha[2].length == 4){ //Es el anio
        return arrFecha[2] + '-' + arrFecha[1] + '-' + arrFecha[0];
    } else {
        return arrFecha[0] + '-' + arrFecha[1] + '-' + arrFecha[2];
    }
}

function dibujarDetallePlanificacion(){
    $('#fechaInicio').val(transformarFechaParaInput(PlanificacionJSON.fechaInicio));
    $('#fechaFin').val(transformarFechaParaInput(PlanificacionJSON.fechaFin));
    $('#horaInicio').val(PlanificacionJSON.horaInicio);
    $('#horaFin').val(PlanificacionJSON.horaFin);
    $('#titulo').val(PlanificacionJSON.titulo);
    $('#observaciones').val(PlanificacionJSON.observaciones);
}

function cargarSelectores(nombreSelector, arreglo) {
    for (var i = 0; i < arreglo.length; i++){
        var seccion = arreglo[i];
        var option = $("<option></option>")
                            .attr("value", seccion.id)
                            .text(seccion.descripcion);

        $('#'+nombreSelector).append(option);
    }
}


function dibujarSelectFormulario(){
    var operariosNoRelacionadas =  arrOperariosJSON[0];
    cargarSelectores('operariosPlanificacion_1', operariosNoRelacionadas) ;
    var operariosRelacionadas =  arrOperariosJSON[1];
    cargarSelectores('operariosPlanificacion_2', operariosRelacionadas) ;
   
}

function dibujarDatosOrdenDeCompra(){
    if (TareaJSON.ordenDeCompra.hasOwnProperty('id')){
        //Por el momento el numero de la orden de compra va a ser el ID
        $('#nroOrdenDeCompra').val(TareaJSON.ordenDeCompra.id);
        $('#fechaLiberacion').val(TareaJSON.ordenDeCompra.fechaLiberacion);
    }
    
    if (TareaJSON.solicitante.hasOwnProperty('id')){
        $('#solicitanteOrdenDeCompra').val(TareaJSON.solicitante.nombre + ', ' + TareaJSON.solicitante.apellido);
    }
    
    if (TareaJSON.solicitante.hasOwnProperty('id')){
        $('#ejecutorOrdenDeCompra').val(TareaJSON.ejecutor.nombre + ', ' + TareaJSON.ejecutor.apellido);
    }
    
    $('#descripcionOrdenDeCompra').val(TareaJSON.descripcion);
}

</script>