<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Asignar Perfiles Firmantes al Formulario</h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formFormulario" name="formFormulario">
                    <div class="form-row mt-5">
                        <div class="col-lg-6">
                            <div class="form-row">
                                <div class="col-md-2">
                                    <label for="formularioNombre">Formulario:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="formularioNombre" name="formularioNombre" class="form-control" readonly="true">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-row">
                                <div class="col-md-2">
                                    <label for="idPerfil"><?= $this->translate('__Perfil__') ?>:</label>
                                </div>  
                                <div class="col-md-5">
                                    <select id="idPerfil" name="idPerfil" class="form-control">
                                        <option value="-1">-- Seleccione --</option>
                                        <?php foreach($arrPerfiles as $Perfil) :?>
                                            <option value="<?= $Perfil->getId() ?>"><?= $Perfil->getNombre() ?></option>
                                        <?php endforeach;?>
                                    </select>
                                </div>
                                <div class="col-md-1">
                                    <div class="btn btn-primary" onclick="agregarPerfil();"><?= $this->translate('__Agregar__') ?></div>
                                </div>
                            </div>
                            <div class="form-row mt-5">
                                <table class="table table-hover" data-page-size="15">
                                    <thead>
                                        <tr>
                                            <th>Perfiles Firmantes</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody id="bodyPerfiles">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var formularioJSON = <?= $FormularioJSON ?>;
var arrPerfiles = formularioJSON.perfilesFirmantes;

function FormUsuarioToJson(){
    var formData = {
        perfiles: arrPerfiles
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormUsuarioToJson();
    $('#JsonData').val(JsonData);

    $("#formFormulario").submit();
}

$( document ).ready(function() {
    $('#formularioNombre').val(formularioJSON.nombre);
    
    verificarMostrarBotonGuardar();
    actualizarPerfiles();
});

function agregarPerfil(){
    var combo = document.getElementById("idPerfil");
    
    var IdPerfilSeleccionado = combo.value;
    var NombrePerfilSeleccionado =  combo.options[combo.selectedIndex].text;
    
    if(IdPerfilSeleccionado > 0){
        if(!existePerfil(IdPerfilSeleccionado)){
            addPerfil(IdPerfilSeleccionado,NombrePerfilSeleccionado);
        }
        else{
            swal(
                'Perfil duplicado!',
                'El perfil que intenta agregar ya se encuentra cargado.',
                'error'
            );
        }
    }
    else{
        swal(
            'Perfil No Seleccionado!',
            'Seleccione un perfil.',
            'error'
        );  
    }
    actualizarPerfiles();
}

function addPerfil(IdPerfilSeleccionado, NombrePerfilSeleccionado){    
    
    var nuevoPerfil = {
        'id': IdPerfilSeleccionado,
        'nombre' : NombrePerfilSeleccionado
    };
    
    arrPerfiles.push(nuevoPerfil);
}

function agregarBotonBorrarPerfil(contenedor, idPerfil, nombrePerfil){
    var icon = document.createElement('i');
    icon.setAttribute('class','fa p16 fa-trash-alt');

    var div = document.createElement('div');
    div.setAttribute('class','btn btn-danger btn-circle btn-outline');
    div.setAttribute('onclick', 'borrarPerfil(' + idPerfil + ', \'' + nombrePerfil + '\')');

    div.appendChild(icon);

    contenedor.appendChild(div);
}

function actualizarPerfiles(){
   $('#bodyPerfiles').find('tr').remove();

    for (var i = 0; i < arrPerfiles.length; i++)
    {
        var perfil = arrPerfiles[i];

        var body = document.getElementById("bodyPerfiles");
        var row = body.insertRow();

        var nombre = row.insertCell(0);
        var borrar = row.insertCell(1);

        nombre.innerHTML = perfil.nombre;
        agregarBotonBorrarPerfil(borrar, perfil.id, perfil.nombre);
    }
}

function borrarPerfil(IdPerfil, nombre){
    swal({
        title: 'Eliminar Perfil',
        width: 600,
        text: "Esta seguro que desea eliminar el perfil: " + nombre + "?",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText: 'Cancelar',
        confirmButtonText: 'Confirmar'
    }).then((result) => {
        if (result.value) {
            eliminarPerfil(IdPerfil);
            swal(
                'Eliminado!',
                'El perfil ha sido eliminado.',
                'success'
            )
        }
    })  
};

function eliminarPerfil(IdPerfil){
    arrPerfiles.forEach(function(datosFila){
        if (datosFila.id == IdPerfil){
            pos = arrPerfiles.indexOf(datosFila);
            arrPerfiles.splice(pos, 1);
        }
    });
    actualizarPerfiles();
}

function existePerfil(IdPerfil){
    var existe = false;
    arrPerfiles.forEach(function(datosFila){
        if (datosFila.id == IdPerfil){
            existe = true;
        }
    });
    return existe;
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

</script>