<script type="text/javascript" src="<?= $this->basePath('/js/operation/permits/forms/jquery.multi-select.js') ?>"></script>
<script>
    var formulario = <?= $formulario ?>;
    var idList = Array();

    function createListFromJSONLista(selector, lista, seleccione) {
        if (seleccione){
            var option = document.createElement("option");
            option.value =  -1;
            option.text = 'Seleccione';
            selector.appendChild(option);
        }
        
        for (var i=0; i < lista.length; i++) {
            var option = document.createElement("option");
            option.value = lista[i];
            option.text = lista[i];
            selector.appendChild(option);
        }
        return selector;
    }

    function obtenerListaOpciones(lista){
        var output = [];
        for (var i=0; i < lista.length; i++) {
            var item = lista[i];
            output.push(item.descripcion);
        }
        return output;
    }

    function createSimpleSelector(id, opciones, divElement, idSeccion) {
        
        var selector = document.createElement("select");
        idSector = "pregunta_"+id+"_seccion_"+idSeccion;
        selector.id = idSector;
        var opciones = obtenerListaOpciones(opciones);
        var selector = createListFromJSONLista(selector, opciones, true);
        divElement.appendChild(selector);

        idList.push(idSector);
    }

    function createMultipleSelector(id, name, opciones, divElement, size) {
        var selector = document.createElement("select");
        selector.name = name;
        selector.id = id;
        selector.multiple = true;
        selector.className = "form-control";
        selector.size = size;
        selector.style.marginBottom = "5px";
        var opciones = obtenerListaOpciones(opciones);
        var selector = createListFromJSONLista(selector, opciones, false);
        divElement.appendChild(selector);

        idList.push(id);
    }

    function createDivClass(info, div) {
        var divClass = document.createElement("Div");
        divClass.className = info;
        div.appendChild(divClass);
        return divClass;
    }

    function insertarElementInSelect(origin, destination, id, idSeccion){
        console.log(origin+id+"_seccion_"+idSeccion);
        console.log(destination+id+"_seccion_"+idSeccion);
        var select1 = document.getElementById(origin+id+"_seccion_"+idSeccion);
        console.log(select1);
        var selected1 = [];
        for (var i = 0; i < select1.length; i++) {
            if (select1.options[i].selected) {
                selected1.push(select1.options[i].value);
                console.log(select1.options[i].value);
            }
        }
        
        var optionOrigin = deleteOptions(origin+id+"_seccion_"+idSeccion);
        var selectIn = document.getElementById(destination+id+"_seccion_"+idSeccion);
        console.log(selectIn);
        createListFromJSONLista(selectIn, selected1, false);
        manageButtons(id, idSeccion);
    }

    function createButton(infoType, id, title, divElement, icon, disabled, origin, destination, idPregunta, idSeccion){
        var button = document.createElement("button");
        button.type = infoType;
        button.id = id;
        button.title = title;
        button.className = "btn btn-primary";
        button.textContent = icon;
        button.disabled = disabled;
        button.style.marginTop = "15px";
        button.onclick = function() {insertarElementInSelect(origin, destination, idPregunta, idSeccion)};

        
        // var icono = document.createElement("i");
        // icono.className = "fas fa-angle-left";
        // button.appendChild(icono);
        divElement.appendChild(button);
    }

    function removeAllOptionSelector(origin){
        $('#'+origin).find('option')
            .remove()
            .end();
    }

    function deleteOptions(origin) {
        var select1 = document.getElementById(origin);
        var notSelected = [];
        for (var i = 0; i < select1.length; i++) {
            if (!select1.options[i].selected) notSelected.push(select1.options[i].value);
        }
        removeAllOptionSelector(origin);
        createListFromJSONLista(select1, notSelected, false);
    }

    function manageButtons(id, idSeccion){
        if($('#Origen_id_'+id+"_seccion_"+idSeccion+' option').length == 0){
            $("#PositiveR_id_"+id+"_seccion_"+idSeccion).prop('disabled', true);
            $("#NegativeR_id_"+id+"_seccion_"+idSeccion).prop('disabled', true);
        } else {
            $("#PositiveR_id_"+id+"_seccion_"+idSeccion).prop('disabled', false);
            $("#NegativeR_id_"+id+"_seccion_"+idSeccion).prop('disabled', false);
        }
        if($('#Positive_id_'+id+"_seccion_"+idSeccion+' option').length == 0){
            $("#PositiveL_id_"+id+"_seccion_"+idSeccion).prop('disabled', true);
        } else {
            $("#PositiveL_id_"+id+"_seccion_"+idSeccion).prop('disabled', false);
        }
        if($('#Negative_id_'+id+"_seccion_"+idSeccion+' option').length == 0){
            $("#NegativeL_id_"+id+"_seccion_"+idSeccion).prop('disabled', true);
        } else {
            $("#NegativeL_id_"+id+"_seccion_"+idSeccion).prop('disabled', false);
        }
    }

    function createMultipleSelectorSkeleton(id, opciones, opciones_in, opciones_out, divElement, idSeccion){
        var divForm = createDivClass("form-row", divElement);
        var divRow = createDivClass("row", divForm);
        var div_class_sm_3 = createDivClass("col-sm-3", divRow);
        createMultipleSelector('Origen_id_'+id+"_seccion_"+idSeccion, id, opciones, div_class_sm_3, 10);

        var div_class_sm_1 = createDivClass("col-sm-1", divRow);
        createButton("button", "PositiveR_id_"+id+"_seccion_"+idSeccion, "Añadir seleccionados", div_class_sm_1, ">", false, "Origen_id_", "Positive_id_", id,idSeccion);
        createButton("button", "PositiveL_id_"+id+"_seccion_"+idSeccion, "Quitar seleccionados", div_class_sm_1, "<", true, "Positive_id_", "Origen_id_", id,idSeccion);
        createButton("button", "NegativeR_id_"+id+"_seccion_"+idSeccion, "Añadir seleccionados", div_class_sm_1, ">", false, "Origen_id_", "Negative_id_", id,idSeccion);
        createButton("button", "NegativeL_id_"+id+"_seccion_"+idSeccion, "Quitar seleccionados", div_class_sm_1, "<", true, "Negative_id_", "Origen_id_", id,idSeccion);

        var div_class_sm_3_2 = createDivClass("col-sm-3", divRow);
        createMultipleSelector('Positive_id_'+id+"_seccion_"+idSeccion, id, opciones_in, div_class_sm_3_2, 5);
        createMultipleSelector('Negative_id_'+id+"_seccion_"+idSeccion, id, opciones_out, div_class_sm_3_2, 5);
        var div_class_sm_5 = createDivClass("col-sm-5", divRow);
    }
    function updateJson(idSeccion, idPregunta, idRespuesta) {
        childs = formulario.secciones;
        for (var i = 0; i < childs.length; i++){
            if(childs[i].id == idSeccion){
                preguntas = childs[i].preguntas;
                for (var j = 0; j < preguntas.length; j++){
                    if(preguntas[j].id == idPregunta){
                        preguntas[j].respuesta = $("#"+idRespuesta).val();
                        console.log(idRespuesta);
                        console.log($("#"+idRespuesta).val());
                        console.log(preguntas[j].respuesta );
                    }
                }
            }
        }
       
    }

    function createInput(infoType, idPregunta, divElement, idSeccion){
        console.log(idPregunta);
        ele = document.createElement('input');
        ele.type = infoType;
        idEle = "pregunta_"+idPregunta+"_seccion_"+idSeccion;
        console.log(idEle);
        ele.name = idEle;
        ele.id = idEle;
        ele.onchange = function() {updateJson(idSeccion, idPregunta, idEle)};
        // accept = getInputAccept(item);
        // ele.accept= accept;
        // ele.accept="image/png, image/jpeg"
        divElement.appendChild(ele);

        // idList.push(idEle);
    } 

    function createOptions(item, divElement, idSeccion){
        if(item.tipoPregunta.descripcion == 'simple'){
            var opciones = item.opciones;
            createSimpleSelector(item.id, opciones, divElement, idSeccion);
        } else if(item.tipoPregunta.destinos == 1) {
            var opciones = item.opciones;
            createMultipleSelectorSkeleton(item.id, opciones, [],[], divElement, idSeccion);
        } else {
            //luego
        }
    }

    function createTextArea(item, divElement, idSeccion){
        ele = document.createElement('textarea');
        id = "pregunta_"+item.id+"_seccion_"+idSeccion;
        ele.name = id;
        ele.id = id;
        divElement.appendChild(ele);
        ele.onchange = function() {updateJson(idSeccion, item.id, id)};

        // idList.push(id);
    }

    function createImage(item, divElement, idSeccion){
        ele = document.createElement('img');
        ele.src = "#";
        id = "pregunta_"+item.id+"_seccion_"+idSeccion;
        ele.name = id;
        ele.id = id;
        divElement.appendChild(ele);

        // idList.push(id);
    }
    
    function createAnswer(item, divElement, idSeccion){
        if (item.cerrada == '1'){
            createOptions(item, divElement, idSeccion);
        } else {
            if(item.tipoPregunta.descripcion == 'image'){
                createImage(item, divElement, idSeccion);
            } else if(item.tipoPregunta.descripcion == 'textarea'){
                createTextArea(item, divElement, idSeccion);
            } else {
                console.log(item.id);
                createInput(item.tipoPregunta.descripcion, item.id, divElement, idSeccion);
            }
        }
    }

    function createTextElement(type, div, info){
        var element = document.createElement(type);
        var text = document.createTextNode(info);
        element.appendChild(text);
        div.appendChild(element);
    }

    function createQuestions(item, divElement){
        preguntas = item.preguntas;
        for (var i = 0; i < preguntas.length; i++){
            var div = document.createElement("Div");
            div.className='row';
            div.style.padding = "15px";
            divElement.appendChild(div);
            var item2 = preguntas[i];
            createTextElement("P", div, item2.descripcion);
            createAnswer(item2, div, item.id);
        }
    }

    function crearItemSeccion(item, contenedor){

        // Creating a div element
        var divElement = document.createElement("Div");
        divElement.id = "Seccion_id_"+item.id;
        divElement.style.padding = "10px";
        divElement.className="form-row";
        divElement.style.textAlign = "lefth";

        var divSeleccion = createDivClass("row", divElement);
        var div_class_sm_1 = createDivClass("col-sm-1", divSeleccion);
        createTextElement("h4", div_class_sm_1, item.nombre);

        createQuestions(item, divElement);
        contenedor.appendChild(divElement);
        
        return divElement;
    }

    function construirSecciones(childs, contenedor){
        for (var i = 0; i < childs.length; i++){
            var item = childs[i];
            var itemSeccion = crearItemSeccion(item, contenedor);
            contenedor.appendChild(itemSeccion);
        }
    }

    // function createHref(info, divElement){
    //     ele = document.createElement('a');
    //     ele.href = info;
    //     divElement.appendChild(ele);

    //     var div = document.createElement("Div");
    //     div.className = "btn";

    //     var text = document.createTextNode("Cancelar");
    //     div.appendChild(text);
    //     ele.appendChild(div);
    // }

    function updateInput() {
        var datos  = [];
        var objeto = {};
        
        for(var i= 0; i < idList.length; i++) {
            var nombre = idList[i]
            datos.push({ 
                "id"    : idList[i],
                "respuesta"  : $("#"+idList[i]).val(),
            });
        }
        objeto.datos = datos;

        var json = JSON.stringify(objeto);
        console.log(json);

        $("#JsonData").val(json);
    }

    function createFormulario(){
        var contenedor = document.getElementsByTagName("div")[0];

        var divFormulario = document.createElement("Div");
        divFormulario.id = "Formulario_id_"+formulario.id;
        divFormulario.style.paddingTop = "15px";
        createTextElement("h3", divFormulario, formulario.descripcion);
        contenedor.appendChild(divFormulario);

        construirSecciones(formulario.secciones, divFormulario);
    }

    createFormulario();
</script>
<form method="post"  action="<?=$this->url("formulario/show-form",["action" => "showForm"])?>" name="formPerfil" >
    <div class="row">
        <input type="hidden" name="JsonData" id="JsonData">
        <a href="#">
            <div class="btn btn-primary">Cancelar</div>
        </a>
        <button id="submit" class="btn btn-primary" type="submit" onclick="updateInput()">Confirmar</button>
    </div>
</form>
