<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Tareas</h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaTareas" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Resumen</th>
                            <th class="text-center">Solicitante</th>
                            <th class="text-center">Nodo</th>
                            <th class="text-center">Estado</th>
                            <th class="text-center">Fecha de Solicitud</th>
                            <th class="text-center">Formulario</th>
                        </tr>
                    </thead>
                    <tbody id="bodyTareas">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrTareasJSON = <?= $arrTareasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaTareas();
    });

    function dibujarTablaTareas(){
        $('#bodyTareas').find('tr').remove();
    
        for (var i = 0; i < arrTareasJSON.length; i++)
        {
            var tarea = arrTareasJSON[i];

            var body = document.getElementById("bodyTareas");
            var row = body.insertRow();
            row.id = i;

            var resumen = row.insertCell(0);
            var solicitante = row.insertCell(1);
            var nodo = row.insertCell(2);
            var estado = row.insertCell(3);
            var fecha = row.insertCell(4);
            var formulario = row.insertCell(5);

            resumen.innerHTML = tarea.resumen;
            solicitante.innerHTML = tarea.solicitante.nombre + ', ' + tarea.solicitante.apellido;
            nodo.innerHTML = tarea.nodo.nombre;
            estado.innerHTML = tarea.estadoTarea.descripcion;

            //var date = new Date(tarea.fechaSolicitud);

            fecha.innerHTML = tarea.fechaSolicitud;
            formulario.innerHTML = tarea.relevamiento.formulario.nombre;
        }
    }

    $(function() {
        $('#tablaTareas').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function preEditar(){
        if (filaSeleccionada >= 0){
            var tarea = arrTareasJSON[filaSeleccionada];

            window.location.replace(url + "/formulario/cargar/" + tarea.id);
        }else{
            swal('Tarea no seleccionado',
                'Por favor seleccione la tarea que desea editar',
                'error');
        }
    }

  </script>