<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Planificaciones__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaTareas" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Tarea_ID__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nro_etapa_dia__') ?></th>
                            <th class="text-center"><?= $this->translate('__Solicitante__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nodo__') ?></th>
                            <th class="text-center"><?= $this->translate('__Estado__') ?></th>
                            <th class="text-center"><?= $this->translate('__Fecha_de_Solicitud__') ?></th>
                            <th class="text-center"><?= $this->translate('__Acciones__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyTareas">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrTareasJSON = <?= $arrTareasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaTareas();
    });

    function dibujarTablaTareas(){
        $('#bodyTareas').find('tr').remove();
    
        for (var i = 0; i < arrTareasJSON.length; i++)
        {
            var tarea = arrTareasJSON[i];

            var body = document.getElementById("bodyTareas");


            for(var j = 0; j < tarea.planificaciones.length; j++){
                var planificacion = tarea.planificaciones[j];
            //    console.log(planificacion.relevamiento);
                if (planificacion.relevamiento.hasOwnProperty('secciones')){
                    var row = body.insertRow();
                    row.id = planificacion.id;

                    var tareaID = row.insertCell(0);
                    var nroEtapaDia = row.insertCell(1);
                    var solicitante = row.insertCell(2);
                    var nodo = row.insertCell(3);
                    var estado = row.insertCell(4);
                    var fecha = row.insertCell(5);
                    var acciones = row.insertCell(6);

                    tareaID.innerHTML = tarea.id;
                    nroEtapaDia.innerHTML = planificacion.diaEtapa; 
                    solicitante.innerHTML = tarea.solicitante.nombre + ', ' + tarea.solicitante.apellido;
                    nodo.innerHTML = tarea.nodo.nombre;
                    estado.innerHTML = planificacion.relevamiento.estadoRelevamiento.descripcion;
                    fecha.innerHTML = tarea.fechaSolicitud;
                    dibujarAccionesDePlanificacion(acciones, planificacion);
                }   
            }
        }
    }

    /**
     * Funcion que muestra el boton de cerrado de un permiso de trabajo.
     */
    function agregarBotonCerrarPermiso(contenedor, planificacion){
        var icon = document.createElement('i');
        icon.setAttribute('class','fas p16 fa-lock');

        var a = document.createElement('a');
        a.setAttribute('class','btn btn-primary btn-circle btn-outline');
        a.setAttribute('href', url + '/formulario/para-firmar/' +planificacion.id);

        a.appendChild(icon);

        contenedor.appendChild(a);
    }

    /**
     * Funcion que muestra el boton de ver PDF de un permiso de trabajo.
     */
    function agregarBotonVerPDF(contenedor, planificacion){
        var icon = document.createElement('i');
        icon.setAttribute('class','far p16 fa-file-pdf');

        var a = document.createElement('a');
        a.setAttribute('class','btn btn-success btn-circle btn-outline');
        a.setAttribute('target', '_blank');
        a.setAttribute('href', url + '/formulario/imprimir/' +planificacion.relevamiento.id);

        a.appendChild(icon);

        contenedor.appendChild(a);
    }

    function dibujarAccionesDePlanificacion(contenedor, planificacion){
        var divFila = document.createElement('div');
        divFila.setAttribute('class','form-row');

        if (planificacion.relevamiento.estadoRelevamiento.esEditado){
            var divCerrar = document.createElement('div');
            divCerrar.setAttribute('class','col-md-6');
            
            agregarBotonCerrarPermiso(divCerrar, planificacion);
            
            divFila.appendChild(divCerrar);
        }

        if (planificacion.relevamiento.estadoRelevamiento.esFinalizado){
            var divPDF = document.createElement('div');
            divPDF.setAttribute('class','col-md-6');
            
            agregarBotonVerPDF(divPDF, planificacion);
            
            divFila.appendChild(divPDF);
        }

        contenedor.appendChild(divFila);
    }

    function buscarPlanificacionPorId(){
        for (var i = 0; i < arrTareasJSON.length; i++){
            var tarea = arrTareasJSON[i];

            for (var j = 0; j < tarea.planificaciones.length; j++){
                var planificacion = tarea.planificaciones[j];

                if (planificacion.id == filaSeleccionada){
                    return planificacion;
                }
            }
        }
    }

    $(function() {
        $('#tablaTareas').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                var planificacion = buscarPlanificacionPorId();

                if (planificacion.relevamiento.estadoRelevamiento.esEditado
                    || planificacion.relevamiento.estadoRelevamiento.esParaEditar){
                    cambiarVisibilidadBotones(true);
                }else{
                    cambiarVisibilidadBotones(false);
                }
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function preEditar(){
        if (filaSeleccionada >= 0){
            //La fila seleccionada ya tiene el id de la planificacin
            window.location.replace(url + "/formulario/cargar/" + filaSeleccionada);
        }
    }

  </script>