<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Planificaciones__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaTareas" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Tarea_ID__') ?></th>
                            <th class="text-center"><?= $this->translate('__Solicitante__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nodo__') ?></th>
                            <th class="text-center"><?= $this->translate('__Estado__') ?></th>
                            <th class="text-center"><?= $this->translate('__Fecha_de_Solicitud__') ?></th>
                            <th class="text-center"><?= $this->translate('__Formulario__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyTareas">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrTareasJSON = <?= $arrTareasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaTareas();
    });

    function dibujarTablaTareas(){
        $('#bodyTareas').find('tr').remove();
    
        for (var i = 0; i < arrTareasJSON.length; i++)
        {
            var tarea = arrTareasJSON[i];

            var body = document.getElementById("bodyTareas");


            for(var j = 0; j < tarea.planificaciones.length; j++){
                var planificacion = tarea.planificaciones[j];
                
                if (planificacion.relevamiento.hasOwnProperty('formulario')){
                    var row = body.insertRow();
                    row.id = planificacion.id;

                    var tareaID = row.insertCell(0);
                    var solicitante = row.insertCell(1);
                    var nodo = row.insertCell(2);
                    var estado = row.insertCell(3);
                    var fecha = row.insertCell(4);
                    var formulario = row.insertCell(5);

                    tareaID.innerHTML = tarea.id;
                    solicitante.innerHTML = tarea.solicitante.nombre + ', ' + tarea.solicitante.apellido;
                    nodo.innerHTML = tarea.nodo.nombre;
                    estado.innerHTML = planificacion.relevamiento.estadoRelevamiento.descripcion;

                    fecha.innerHTML = tarea.fechaSolicitud;
                    formulario.innerHTML = planificacion.relevamiento.formulario.nombre;
                }   
            }
        }
    }

    $(function() {
        $('#tablaTareas').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function preEditar(){
        if (filaSeleccionada >= 0){
            //La fila seleccionada ya tiene el id de la planificacin
            window.location.replace(url + "/formulario/cargar/" + filaSeleccionada);
        }else{
            swal('Tarea no seleccionado',
                'Por favor seleccione la tarea que desea editar',
                'error');
        }
    }

  </script>