<div class="form-row" id="divPreguntas">
    <div class="col-md-12">
        <div class="panel panel-default mt-5">
            <div class="panel-heading">
                <h5 class="panel-title"><?= $this->translate('__Listado_de_todas_las_Preguntas__') ?></h5>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaPreguntas" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Numero__') ?></th>
                            <th class="text-center"><?= $this->translate('__Pregunta__') ?></th>
                            <th class="text-center"><?= $this->translate('__Tipo_de_Pregunta__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyConfPreguntas">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrPreguntasJSON = <?= $arrPreguntasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaPreguntas();
    });

    function dibujarTablaPreguntas(){
        $('#bodyConfPreguntas').find('tr').remove();

        for (var i = 0; i < arrPreguntasJSON.length; i++)
        {
            var pregunta = arrPreguntasJSON[i];

            var body = document.getElementById("bodyConfPreguntas");
            var row = body.insertRow();
            row.id = i;

            var id = row.insertCell(0);
            var nombre = row.insertCell(1);
            var tipo = row.insertCell(2);
            var pertenece = row.insertCell(3);
            var requerida = row.insertCell(4);

            id.innerHTML = pregunta.idPregunta;
            nombre.innerHTML = pregunta.descripcion;
            tipo.innerHTML = pregunta.tipoPregunta.informacion;
        }
    }

    $(function() {
        $('#tablaPreguntas').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');
                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;
                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarPregunta() {
        var result = null;
        var pregunta = arrPreguntasJSON[filaSeleccionada];
        $.ajax({
            url: url + '/configuracion/preguntas/borrar-pregunta/' + pregunta.idPregunta,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var pregunta = arrPreguntasJSON[filaSeleccionada];
            
            swal({
                title: '<?= $this->translate('__Eliminar_Pregunta__') ?>',
                width: 600,
                text: "<?= $this->translate('__mensaje_eliminar_pregunta__') ?>: "+ pregunta.idPregunta +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarPregunta();
                    window.location.replace(url + "/configuracion/preguntas");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var pregunta = arrPreguntasJSON[filaSeleccionada];
            console.log(arrPreguntasJSON);
            console.log(filaSeleccionada);

            window.location.replace(url + "/configuracion/preguntas/editar-pregunta/" + pregunta.idPregunta);
        }
    }

  </script>