<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de ABM</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "accion", "action" => "listar"])?>">Acciones</a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "operacion", "action" => "listar"])?>">Operaciones</a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "perfiles", "action" => "listar"])?>">Perfiles</a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "usuarios", "action" => "listar"])?>">Usuarios</a>
                </div>
                <div class="row">
                    <a href="<?=$this->url("abm/entidad",["entidad" => "operacionAccionPerfil", "action" => "listar"])?>">Acciones - Operaciones Por Perfil</a>
                </div>
            </div>
        </div>
    </div>

</div>