<div class="form-row">
    
        <div class="col-md-3">
            <a href="<?=$this->url("abm/entidad",["entidad" => "accion", "action" => "alta"])?>">Nueva Acción</a>
        </div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Listado de Acciones</h3>
                </div>
                <div class="panel-body">
                    <table class="footable table table-stripped toggle-arrow-tiny no-borders">
                        <thead>
                            <tr>
                                <th class="text-center">Nombre</th>
                                <th class="text-center">Titulo</th>
                                <th class="text-center">Icono</th>
                                <th class="text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody id="">
                        <?php foreach($arrEntidades as $Accion) : ?>
                            <tr>
                                <td><?= $Accion->getNombre() ?></td>
                                <td><?= $Accion->getTitulo() ?></td>
                                <td><?= $Accion->getIcono() ?></td>
                                <td>
                                    <a href="<?=$this->url("abm/entidad",
                                        ["entidad" => "accion", "action" => "editar", "id" => $Accion->getId()]
                                        )?>">Editar</a> | 
                                    <a href="<?=$this->url("abm/entidad",
                                        ["entidad" => "accion", "action" => "borrar", "id" => $Accion->getId()]
                                        )?>">Borrar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div class="flex">
                        <a href="<?=$this->url("abm",["action" => "listar"])?>">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>