<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nuevo Perfil</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="<?=$this->url("abm/entidad",["entidad" => "perfiles", "action" => "alta"])?>" name="formAltaPerfil" onsubmit="preSubmit()">
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="nombrePerfil"><span class="obligatorio">(*) </span>Nombre:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="nombrePerfil" name="nombrePerfil" class="form-control" required="true"
                            value="<?= ($Entidad) ? $Entidad->getNombre() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="descripcionPerfil">Descripción:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="descripcionPerfil" name="descripcionPerfil" class="form-control"
                            value="<?= ($Entidad) ? $Entidad->getDescripcion() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <input type="hidden" name="JsonData" id="JsonData">
                        <a href="<?=$this->url("abm/entidad",["entidad" => "perfiles", "action" => "listar"])?>">
                            <div class="btn">Cancelar</div>
                        </a>
                        <button type="submit">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
function FormAltaPerfilToJson(){
    var formData = {
        nombre: $('#nombrePerfil').val(), 
        descripcion: $('#descripcionPerfil').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormAltaPerfilToJson();
    $('#JsonData').val(JsonData);

    if ($("#formAltaPerfil")[0].checkValidity()){
        $("#formAltaPerfil").submit();
    }else{
        $("#formAltaPerfil")[0].reportValidity();
    }
}
</script>