<div class="form-row">
    
        <div class="col-md-3">
            <a href="<?=$this->url("abm/entidad",["entidad" => "operacionAccionPerfil", "action" => "alta"])?>">Nueva Relación</a>
        </div>
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Listado de Operaciones - Acciones - Perfiles</h3>
                </div>
                <div class="panel-body">
                    <table>
                        <thead>
                            <tr>
                                <th>Operación</th>
                                <th>Acción</th>
                                <th>Perfil</th>
                                <th class="text-right">Acciones</th>
                            </tr>
                        </thead>
                        <tbody id="">
                        <?php foreach($arrEntidades as $Entidad) : ?>
                            <tr>
                                <td><?= $Entidad->getOperacion()->getTitulo() ?></td>
                                <td><?= $Entidad->getAccion()->getNombre() ?></td>
                                <td><?= $Entidad->getPerfil()->getNombre() ?></td>
                                <td></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>