<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("configuracion/tipo-pregunta",["action" => "alta"])?>">Nuevo Tipo Pregunta</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Tipos de Preguntas</h3>
            </div>
            <div class="panel-body">
                <table id="tablaTipoPregunta" class="footable table table-stripped toggle-arrow-tiny no-borders">
                    <thead>
                        <tr>
                            <th class="text-center">Descripcion</th>
                            <th class="text-center">Cant. Destinos</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrTipoPreguntas as $TipoPregunta) : ?>
                        <tr id="<?= $TipoPregunta->getId() ?>">
                            <td><?= $TipoPregunta->getDescripcion() ?></td>
                            <td><?= $TipoPregunta->getCantDestinos() ?></td>
                            <td>
                                <a href="<?=$this->url("configuracion/tipo-pregunta",
                                                    ["action" => "editar", "id" => $TipoPregunta->getId()])?>">editar</a> | 
                                <a href="<?=$this->url("configuracion/tipo-pregunta",
                                                    ["action" => "borrar", "id" => $TipoPregunta->getId()])?>">borrar</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script>
    var filaSeleccionada = -1;

    $(function() {
        $('#tablaTipoPregunta').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
            }
        });
    });

    function borrarTipoPregunta() {
        var result = null;
        
        $.ajax({
            url: url + '/configuracion/tipo-pregunta/borrar/' + filaSeleccionada,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                location.reload(true);
                // result = data.esValido;
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada > 0){
            swal({
                title: 'Eliminar Tipo de Pregunta',
                width: 600,
                text: "Esta seguro que desea eliminar el tipo de pregunta?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: 'Cancelar',
                confirmButtonText: 'Confirmar'
            }).then((result) => {
                if (result.value) {
                    borrarTipoPregunta();
                }
            });
        }else{
            swal('Tipo de Pregunta no seleccionada',
                'Por favor seleccione el tipo de pregunta que desea eliminar',
                'error');
        }
        
    }
  </script>