<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("configuracion/tipo-pregunta",["action" => "alta"])?>">Nuevo Tipo Pregunta</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Tipos de Preguntas</h3>
            </div>
            <div class="panel-body">
                <table>
                    <thead>
                        <tr>
                            <th>Descripcion</th>
                            <th>Cant. Destinos</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrTipoPreguntas as $TipoPregunta) : ?>
                        <tr>
                            <td><?= $TipoPregunta->getDescripcion() ?></td>
                            <td><?= $TipoPregunta->getCantDestinos() ?></td>
                            <td>
                                <a href="<?=$this->url("configuracion/tipo-pregunta",
                                                    ["action" => "editar", "id" => $TipoPregunta->getId()])?>">editar</a> | 
                                <a href="<?=$this->url("configuracion/tipo-pregunta",
                                                    ["action" => "borrar", "id" => $TipoPregunta->getId()])?>">borrar</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>