<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Asignar_Permiso_a_la_Planificacion__') ?></h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formPlanificacion" name="formPlanificacion">
                    <div class="form-row mt-5">
                        <div class="col-lg-5">
                            <div class="form-row">
                                <div class="col-md-5">
                                    <label for="nroOrdenDeCompra"><?= $this->translate('__Orden_de_Compra__') ?> Nº:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="nroOrdenDeCompra" name="nroOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-5">
                                    <label for="fechaLiberacion"><?= $this->translate('__Fecha_de_Liberacion__') ?>:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="fechaLiberacion" name="fechaLiberacion" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="solicitanteOrdenDeCompra"><?= $this->translate('__Solicitante__') ?>:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="solicitanteOrdenDeCompra" name="solicitanteOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="ejecutorOrdenDeCompra"><?= $this->translate('__Ejecutor__') ?>:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="ejecutorOrdenDeCompra" name="ejecutorOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="descripcionOrdenDeCompra"><?= $this->translate('__Descripcion__') ?>:</label>
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-11">
                                    <textarea id="descripcionOrdenDeCompra" name="descripcionOrdenDeCompra" class="form-control" readonly="true" rows="12" maxlength="1000"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="form-row">
                                <div class="card" id="divPlanificacion">
                                    <div class="card-header">
                                        <?= $this->translate('__Detalles_de_la_Planificacion__') ?>
                                    </div>
                                    <div class="card-body">
                                        <div class="form-row">
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="fechaInicio"><?= $this->translate('__Fecha_Inicio__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="date" id="fechaInicio" name="fechaInicio" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="fechaFin"><?= $this->translate('__Fecha_Fin__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="date" id="fechaFin" name="fechaFin" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="horaInicio"><?= $this->translate('__Hora_Inicio__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="text" id="horaInicio" name="horaInicio" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-row">
                                                    <div class="col-md-5">
                                                        <label for="horaFin"><?= $this->translate('__Hora_Fin__') ?>:</label>
                                                    </div>
                                                    <div class="col-md-7">
                                                        <input type="text" id="horaFin" name="horaFin" class="form-control" readonly="true">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-2">
                                                <label for="titulo"><?= $this->translate('__Titulo__') ?>:</label>
                                            </div>
                                            <div class="col-md-10">
                                                <input type="text" id="titulo" name="titulo" class="form-control" readonly="true">
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-3">
                                                <label for="observaciones"><?= $this->translate('__Observaciones__') ?>:</label>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-12">
                                                <textarea name="observaciones" id="observaciones" class="form-control" readonly="true"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="formularioPlanificacion"><span class="obligatorio">(*) </span><?= $this->translate('__Formulario__') ?>:</label>
                                </div>
                                <div class="col-md-7">
                                    <select name="formularioPlanificacion" id="formularioPlanificacion" class="form-control" required="true">-- <?= $this->translate('__Seleccione__') ?> --</select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var PlanificacionJSON = <?= $PlanificacionJSON ?>;
var TareaJSON = <?= $TareaJSON ?>;
var arrFormulariosJSON = <?= $arrFormulariosJSON ?>;

function FormPlanificacionToJson(){
    var formulario = {id : $('#formularioPlanificacion').val()};

    var formData = {
        formulario : formulario
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormPlanificacionToJson();
    $('#JsonData').val(JsonData);

    if ($("#formPlanificacion")[0].checkValidity()){
        $("#formPlanificacion").submit();
    }else{
        $("#formPlanificacion")[0].reportValidity();
    }
}

$( document ).ready(function() {
    dibujarDatosOrdenDeCompra();
    dibujarSelectFormulario();
    dibujarDetallePlanificacion();
    if (PlanificacionJSON.relevamiento.hasOwnProperty('formulario')){
        $('#formularioPlanificacion').val(PlanificacionJSON.relevamiento.formulario.idFormulario);
    }
    
    verificarMostrarBotonGuardar();
});

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

function transformarFechaParaInput(fecha){
    var arrFecha = fecha.split('-');
    //[0] => dia; [1] => mes; [2] => anio

    return arrFecha[2] + '-' + arrFecha[1] + '-' + arrFecha[0];
}

function dibujarDetallePlanificacion(){
    $('#fechaInicio').val(transformarFechaParaInput(PlanificacionJSON.fechaInicio));
    $('#fechaFin').val(transformarFechaParaInput(PlanificacionJSON.fechaFin));
    $('#horaInicio').val(PlanificacionJSON.horaInicio);
    $('#horaFin').val(PlanificacionJSON.horaFin);
    $('#titulo').val(PlanificacionJSON.titulo);
    $('#observaciones').val(PlanificacionJSON.observaciones);
}

function dibujarSelectFormulario(){
    $('#formularioPlanificacion')
        .find('option')
        .remove();

    $('#formularioPlanificacion')
        .append($("<option></option>")
            .attr("value", '')
            .text('-- <?= $this->translate('__Seleccione__') ?> --'));

    for (var i = 0; i < arrFormulariosJSON.length; i++){
        var formulario = arrFormulariosJSON[i];

        var option = $("<option></option>")
                            .attr("value", formulario.idFormulario)
                            .text(formulario.nombre);

        $('#formularioPlanificacion').append(option);
    }
}

function dibujarDatosOrdenDeCompra(){
    if (TareaJSON.ordenDeCompra.hasOwnProperty('id')){
        //Por el momento el numero de la orden de compra va a ser el ID
        $('#nroOrdenDeCompra').val(TareaJSON.ordenDeCompra.id);
        $('#fechaLiberacion').val(TareaJSON.ordenDeCompra.fechaLiberacion);
    }
    
    if (TareaJSON.solicitante.hasOwnProperty('id')){
        $('#solicitanteOrdenDeCompra').val(TareaJSON.solicitante.nombre + ', ' + TareaJSON.solicitante.apellido);
    }
    
    if (TareaJSON.solicitante.hasOwnProperty('id')){
        $('#ejecutorOrdenDeCompra').val(TareaJSON.ejecutor.nombre + ', ' + TareaJSON.ejecutor.apellido);
    }
    
    $('#descripcionOrdenDeCompra').val(TareaJSON.descripcion);
}

</script>