<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Editar Acción</h3>
            </div>
            <div class="panel-body">
                <form method="post" name="formEditarAccion" id="formEditarAccion">
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="nombreAccion"><span class="obligatorio">(*) </span>Nombre:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="nombreAccion" name="nombreAccion" class="form-control" required="true"
                            value="<?= ($Entidad) ? $Entidad->getNombre() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="tituloAccion"><span class="obligatorio">(*) </span>Titulo:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="tituloAccion" name="tituloAccion" class="form-control" required="true"
                            value="<?= ($Entidad) ? $Entidad->getTitulo() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">
                            <label for="iconoAccion">Icono:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="iconoAccion" name="iconoAccion" class="form-control"
                            value="<?= ($Entidad) ? $Entidad->getIcono() : '' ?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
function FormAltaAccionToJson(){
    var formData = {
        nombre: $('#nombreAccion').val(), 
        titulo: $('#tituloAccion').val(), 
        icono: $('#iconoAccion').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormAltaAccionToJson();
    $('#JsonData').val(JsonData);

    if ($("#formEditarAccion")[0].checkValidity()){
        $("#formEditarAccion").submit();
    }else{
        $("#formEditarAccion")[0].reportValidity();
    }
}

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

$( document ).ready(function() {
    verificarMostrarBotonGuardar();
});
</script>