<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Formularios__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaFormularios" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Numero__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nombre__') ?></th>
                            <th class="text-center"><?= $this->translate('__Descripcion__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyConfFormularios">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrFormulariosJSON = <?= $arrFormulariosJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaFormularios();
    });

    function dibujarTablaFormularios(){
        $('#bodyConfFormularios').find('tr').remove();
    
        for (var i = 0; i < arrFormulariosJSON.length; i++)
        {
            var formulario = arrFormulariosJSON[i];

            var body = document.getElementById("bodyConfFormularios");
            var row = body.insertRow();
            row.id = i;

            var id = row.insertCell(0);
            var nombre = row.insertCell(1);
            var descripcion = row.insertCell(2);

            id.innerHTML = formulario.idFormulario;
            nombre.innerHTML = formulario.nombre;
            descripcion.innerHTML = formulario.descripcion;
        }
    }

    $(function() {
        $('#tablaFormularios').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarFormulario() {
        var result = null;
        var formulario = arrFormulariosJSON[filaSeleccionada];

        $.ajax({
            url: url + '/configuracion/formularios/borrar-formulario/' + formulario.idFormulario,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var formulario = arrFormulariosJSON[filaSeleccionada];
            
            swal({
                title: '<?= $this->translate('__Eliminar_Formulario__') ?>',
                width: 600,
                text: "<?= $this->translate('__mensaje_eliminar_formulario__') ?>: "+ formulario.idFormulario +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarFormulario();
                    window.location.replace(url + "/configuracion/formularios");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var formulario = arrFormulariosJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/formularios/editar-formulario/" + formulario.idFormulario);
        }
    }


    function preClonar(){
        if (filaSeleccionada >= 0){
            var formulario = arrFormulariosJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/formularios/clonar-formulario/" + formulario.idFormulario);
        }
    }

  </script>