<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Listado_de_Secciones__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaSecciones" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center"><?= $this->translate('__Numero__') ?></th>
                            <th class="text-center"><?= $this->translate('__Nombre__') ?></th>
                            <th class="text-center"><?= $this->translate('__Descripcion__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyConfSecciones">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrSeccionesJSON = <?= $arrSeccionesJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaSecciones();
    });

    function dibujarTablaSecciones(){
        $('#bodyConfSecciones').find('tr').remove();
    
        for (var i = 0; i < arrSeccionesJSON.length; i++)
        {
            var seccion = arrSeccionesJSON[i];

            var body = document.getElementById("bodyConfSecciones");
            var row = body.insertRow();
            row.id = i;

            var id = row.insertCell(0);
            var nombre = row.insertCell(1);
            var descripcion = row.insertCell(2);

            id.innerHTML = seccion.id;
            nombre.innerHTML = seccion.nombre;
            descripcion.innerHTML = seccion.descripcion;
        }
    }

    $(function() {
        $('#tablaSecciones').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function borrarSecciones() {
        var result = null;
        var seccion = arrSeccionesJSON[filaSeleccionada];

        $.ajax({
            url: url + '/configuracion/secciones/borrar-seccion/' + seccion.id,
            type: 'post',
            dataType: 'json',
            async: false,
            success: function (data) {
                
            }
        });
        
        return result;
    }

    function preBorrar(){
        if (filaSeleccionada >= 0){
            var seccion = arrSeccionesJSON[filaSeleccionada];
            
            swal({
                title: '<?= $this->translate('__Eliminar_Seccion__') ?>',
                width: 600,
                text: "<?= $this->translate('__mensaje_eliminar_seccion__') ?>: "+ seccion.id +"?",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '<?= $this->translate('__Cancelar__') ?>',
                confirmButtonText: '<?= $this->translate('__Confirmar__') ?>'
            }).then((result) => {
                if (result.value) {
                    borrarSecciones();
                    window.location.replace(url + "/configuracion/secciones");
                }
            });
        }
    }

    function preEditar(){
        if (filaSeleccionada >= 0){
            var seccion = arrSeccionesJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/secciones/editar-seccion/" + seccion.id);
        }
    }


    function preClonar(){
        if (filaSeleccionada >= 0){
            var seccion = arrSeccionesJSON[filaSeleccionada];

            window.location.replace(url + "/configuracion/secciones/clonar-seccion/" + seccion.id);
        }
    }

  </script>