<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Planificación de Tarea por Día</h3>
            </div>
            <div class="panel-body">
                <form method="post" id="formPlanificacion" name="formPlanificacion">
                    <div class="form-row mt-5">
                        <div class="col-lg-5">
                            <div class="form-row">
                                <div class="col-md-5">
                                    <label for="nroOrdenDeCompra">Orden de Compra Nº:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="nroOrdenDeCompra" name="nroOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-5">
                                    <label for="fechaLiberacion">Fecha de Liberación:</label>
                                </div>
                                <div class="col-md-6">
                                    <input type="text" id="fechaLiberacion" name="fechaLiberacion" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="solicitanteOrdenDeCompra">Solicitante:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="solicitanteOrdenDeCompra" name="solicitanteOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="comitenteOrdenDeCompra">Comitente:</label>
                                </div>
                                <div class="col-md-8">
                                    <input type="text" id="comitenteOrdenDeCompra" name="comitenteOrdenDeCompra" class="form-control" readonly="true">
                                </div>
                            </div>
                            <div class="form-row mt-3">
                                <div class="col-md-3">
                                    <label for="descripcionOrdenDeCompra">Descripcion:</label>
                                </div>
                                <div class="col-md-8">
                                    <textarea id="descripcionOrdenDeCompra" name="descripcionOrdenDeCompra" class="form-control" readonly="true" rows="7" maxlength="1000"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="form-row">
                                <div class="card">
                                    <div class="card-header">
                                        Tarea
                                    </div>
                                    <div class="card-body">
                                        <div class="form-row">
                                            <div class="col-lg-6">
                                                <div class="form-row">
                                                    <div class="col-md-4">
                                                        <label for="diaInicioTarea">Día Inicio:</label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        <input type="date" id="diaInicioTarea" name="diaInicioTarea" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="form-row mt-3">
                                                    <div class="col-md-4">
                                                        <label for="horaInicioTarea">Hora Inicio:</label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        <input type="text" id="horaInicioTarea" name="horaInicioTarea" class="form-control" 
                                                            pattern="[0-9]{2}:[0-9]{2}" max-length="5" placeholder="09:30">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-row">
                                                    <div class="col-md-4">
                                                        <label for="diaFinTarea">Día Fin:</label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        <input type="date" id="diaFinTarea" name="diaFinTarea" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="form-row mt-3">
                                                    <div class="col-md-4">
                                                        <label for="horaFinTarea">Hora Fin:</label>
                                                    </div>
                                                    <div class="col-md-8">
                                                        <input type="text" id="horaFinTarea" name="horaFinTarea" class="form-control"
                                                            pattern="[0-9]{2}:[0-9]{2}" max-length="5" placeholder="19:00">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-3">
                                                <label for="observacionTarea">Observaciones:</label>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-12">
                                                <textarea name="observacionTarea" id="observacionTarea" class="form-control" cols="45" rows="5"></textarea>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <div class="col-md-2 offset-10">
                                                <div class="btn btn-primary" id="AgregaPlanificacion" onclick="agregaPlanificacion()" style="cursor:pointer">Agregar</div>
                                                <div class="btn btn-primary" id="EditaPlanificacion" onclick="editaPlanificacion()" style="cursor:pointer; display: none;">Modificar</div>
                                            </div>
                                        </div>
                                        <div class="form-row mt-3">
                                            <table id="tablaPlanificacion" class="table table-hover" style="display: none;">
                                                <thead>
                                                    <tr>
                                                        <th class="text-center">Día</th>
                                                        <th class="text-center">Inicio</th>
                                                        <th class="text-center">Fin</th>
                                                        <th class="text-center">Acciones</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="bodyPlanificacion">
                                                
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex">
                        <input type="hidden" name="JsonData" id="JsonData">
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
var TareaJson = <?= $TareaJSON ?>;
var arrPlanificacion = TareaJson.planificaciones;

var arrPlanificacionEliminada = [];
var iPosPlanificacionEditada = -1;

function FormPlanificacionToJson(){
    var formData = {
        planificaciones : arrPlanificacion,
        planificacionesEliminadas : arrPlanificacionEliminada
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormPlanificacionToJson();
    $('#JsonData').val(JsonData);

    if ($("#formPlanificacion")[0].checkValidity()){
        $("#formPlanificacion").submit();
    }else{
        $("#formPlanificacion")[0].reportValidity();
    }
}

$( document ).ready(function() {
    // dibujarSelectNodos();
    // dibujarSelectFormulario();

    // if (tareasJson !== ''){
    //     $('#resumenPlanificacion').val(tareasJson.resumen);
    //     $('#descripcionPlanificacion').val(tareasJson.descripcion);
    //     seleccionarNodo();
    //     seleccionarFormulario();
    // }
    
    verificarMostrarBotonGuardar();
});

function verificarMostrarBotonGuardar(){
    for (var i = 0; i < arrAccionesDisponibles.length; i++){
        var boton = arrAccionesDisponibles[i];

        if (boton.jsFunction === 'preSubmit()'){
            $('#'+boton.idHTMLElement).prop('disabled', false);
            $('#'+boton.idHTMLElement).show();
        }
    }
}

function seleccionarNodo(){
    // for (var i = 0; i < arrNodosJSON.length; i++){
    //     var nodo = arrNodosJSON[i];

    //     if (nodo.id == tareasJson.nodo.id){
    //         $('#nodoPlanificacion').val(i);
    //         break;
    //     }
    // }
}

function seleccionarFormulario(){
    // for (var i = 0; i < arrFormularioJSON.length; i++){
    //     var formulario = arrFormularioJSON[i];

    //     if (formulario.idFormulario == tareasJson.relevamiento.formulario.idFormulario){
    //         $('#formularioPlanificacion').val(i);
    //         break;
    //     }
    // }
}

function dibujarSelectNodos(){
    // $('#nodoPlanificacion')
    //     .find('option')
    //     .remove();

    // $('#nodoPlanificacion')
    //     .append($("<option></option>")
    //         .attr("value", -1)
    //         .text('-- Seleccione --'));

    // for (var i = 0; i < arrNodosJSON.length; i++){
    //     var nodo = arrNodosJSON[i];

    //     var option = $("<option></option>")
    //                         .attr("value", i)
    //                         .text(nodo.nombre);

    //     $('#nodoPlanificacion').append(option);
    // }
}

function dibujarSelectFormulario(){
    // $('#formularioPlanificacion')
    //     .find('option')
    //     .remove();

    // $('#formularioPlanificacion')
    //     .append($("<option></option>")
    //         .attr("value", -1)
    //         .text('-- Seleccione --'));

    // for (var i = 0; i < arrFormularioJSON.length; i++){
    //     var formulario = arrFormularioJSON[i];

    //     var option = $("<option></option>")
    //                         .attr("value", i)
    //                         .text(formulario.nombre);

    //     $('#formularioPlanificacion').append(option);
    // }
}

function dibujarDatosOrdenDeCompra(){
    $('#nroOrdenDeCompra').val(TareaJSON.fechaInicio);
    $('#fechaLiberacion').val(TareaJSON.fechaFin);
    $('#solicitanteOrdenDeCompra').val(TareaJSON.horaInicio);
    $('#comitenteOrdenDeCompra').val(TareaJSON.horaFin);
    $('#descripcionOrdenDeCompra').val(TareaJSON.observaciones);
}

function planificacionEstaCompleta(fechaInicio, fechaFin, horaInicio, horaFin, observaciones){
    if (fechaInicio != '' && fechaFin != '' && horaInicio != '' && horaFin != '' && observaciones != ''){
        return true;
    }else{
        return false;
    }
}

function transformarFechaParaMostrar(fecha){
    var arrFecha = fecha.split('-');
    //[0] => anio; [1] => mes; [2] => dia

    return arrFecha[2] + '-' + arrFecha[1] + '-' + arrFecha[0];
}

function agregaPlanificacion(){
    var fechaInicio = $('#diaInicioTarea').val();
    var fechaFin = $('#diaFinTarea').val();
    var horaInicio = $('#horaInicioTarea').val();
    var horaFin = $('#horaFinTarea').val();
    var observaciones = $('#observacionTarea').val();

    if (!planificacionEstaCompleta(fechaInicio, fechaFin, horaInicio, horaFin, observaciones)){
        swal('Información Incompleta',
            'Por favor complete todos los campos de fecha, hora y observaciones.',
            'error');
        
        return;
    }

    var planificacion = {
        fechaInicio : fechaInicio,
        fechaFin : fechaFin,
        horaInicio : horaInicio,
        horaFin : horaFin,
        observaciones : observaciones
    };

    arrPlanificacion.push(planificacion);

    dibujarTablaPlanificacion();
    clearFormularioPlanificacion();
}

function editaPlanificacion(){
    var fechaInicio = $('#diaInicioTarea').val();
    var fechaFin = $('#diaFinTarea').val();
    var horaInicio = $('#horaInicioTarea').val();
    var horaFin = $('#horaFinTarea').val();
    var observaciones = $('#observacionTarea').val();

    if (!planificacionEstaCompleta(fechaInicio, fechaFin, horaInicio, horaFin, observaciones)){
        swal('Información Incompleta',
            'Por favor complete todos los campos de fecha, hora y observaciones.',
            'error');
        
        return;
    }

    var planificacion = {
        fechaInicio : fechaInicio,
        fechaFin : fechaFin,
        horaInicio : horaInicio,
        horaFin : horaFin,
        observaciones : observaciones
    };

    arrPlanificacion.splice(iPosPlanificacionEditada, 1);
    arrPlanificacion.splice(iPosPlanificacionEditada, 0, planificacion);

    dibujarTablaPlanificacion();
    clearFormularioPlanificacion();
}

function cargarPlanificacion(iPosPlanificacion){
    iPosPlanificacionEditada = iPosPlanificacion;

    var planificacion = arrPlanificacion[iPosPlanificacion];

    $('#diaInicioTarea').val(planificacion.fechaInicio);
    $('#diaFinTarea').val(planificacion.fechaFin);
    $('#horaInicioTarea').val(planificacion.horaInicio);
    $('#horaFinTarea').val(planificacion.horaFin);
    $('#observacionTarea').val(planificacion.observaciones);

    $('#AgregaPlanificacion').hide();
    $('#EditaPlanificacion').show();
}

function agregarBotonEditarPlanificacion(contenedor, iPosPlanificacion){
    var icon = document.createElement('i');
    icon.setAttribute('class','fa p16 fa-pencil-alt');

    var div = document.createElement('div');
    div.setAttribute('class','btn btn-primary btn-circle btn-outline');
    div.setAttribute('onclick', 'cargarPlanificacion(' + iPosPlanificacion + ')');

    div.appendChild(icon);

    contenedor.appendChild(div);
}

function agregarBotonBorrarPlanificacion(contenedor, iPosPlanificacion){
    var icon = document.createElement('i');
    icon.setAttribute('class','fa p16 fa-trash-alt');

    var div = document.createElement('div');
    div.setAttribute('class','btn btn-danger btn-circle btn-outline');
    div.setAttribute('onclick', 'confirmarBorrarPlanificacion(' + iPosPlanificacion + ')');

    div.appendChild(icon);

    contenedor.appendChild(div);
}

function agregaBotonesEdicionBorradoPlanificacion(contenedor, iPosPlanificacion){
    var divEditar = document.createElement('div');
    divEditar.setAttribute('class', 'col-md-6');
    agregarBotonEditarPlanificacion(divEditar, iPosPlanificacion);

    var divBorrar = document.createElement('div');
    divBorrar.setAttribute('class', 'col-md-6');
    agregarBotonBorrarPlanificacion(divBorrar, iPosPlanificacion);

    var divFila = document.createElement('div');
    divFila.setAttribute('class', 'form-row');

    divFila.appendChild(divEditar);
    divFila.appendChild(divBorrar);

    contenedor.appendChild(divFila);
}

function confirmarBorrarPlanificacion(iPosPlanificacion){
    var dia = iPosPlanificacion + 1;
    swal({
        title: 'Eliminar Planificación',
        width: 600,
        text: "Esta seguro que desea eliminar la planificaciñon del día: " + dia + "?",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        cancelButtonText: 'Cancelar',
        confirmButtonText: 'Confirmar'
    }).then((result) => {
        if (result.value) {
            eliminarPlanificacion(iPosPlanificacion);
            swal(
                'Eliminada!',
                'La planificacion ha sido eliminada.',
                'success'
            )
        }
    })  
}

function eliminarPlanificacion(iPosPlanificacion){
    var planificacionBorrada = arrPlanificacion.splice(iPosPlanificacion, 1);

    if (planificacionBorrada.hasOwnProperty('id')){
        arrPlanificacionEliminada.push(planificacionBorrada);
    }

    dibujarTablaPlanificacion();
    clearFormularioPlanificacion();
}

function dibujarTablaPlanificacion(){
    $('#bodyPlanificacion').find('tr').remove();

    for (var i = 0; i < arrPlanificacion.length; i++)
    {
        var planificacion = arrPlanificacion[i];

        var body = document.getElementById("bodyPlanificacion");
        var row = body.insertRow();

        var dia = row.insertCell(0);
        var inicio = row.insertCell(1);
        var fin = row.insertCell(2);
        var acciones = row.insertCell(3);

        dia.innerHTML = i+1;
        inicio.innerHTML = transformarFechaParaMostrar(planificacion.fechaInicio) + ' ' + planificacion.horaInicio;
        fin.innerHTML = transformarFechaParaMostrar(planificacion.fechaFin) + ' ' + planificacion.horaFin

        agregaBotonesEdicionBorradoPlanificacion(acciones, i);
    }

    if (arrPlanificacion.length > 0){
        $('#tablaPlanificacion').show();
    }else{
        $('#tablaPlanificacion').hide();
    }
}

function clearFormularioPlanificacion(){
    $('#diaInicioTarea').val('');
    $('#diaFinTarea').val('');
    $('#horaInicioTarea').val('');
    $('#horaFinTarea').val('');
    $('#observacionTarea').val('');

    iPosPlanificacionEditada = -1;
}
</script>