<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Analisis_de_Tareas__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <table id="tablaTareas" class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center"><?= $this->translate('__Fecha__') ?></th>
                            <th class="text-center"><?= $this->translate('__Orden_de_Compra__') ?></th>
                            <th class="text-center"><?= $this->translate('__Solicitante__') ?></th>
                            <th class="text-center"><?= $this->translate('__Ejecutor__') ?></th>
                            <th class="text-center"><?= $this->translate('__Planificacion__') ?></th>
                            <th class="text-center"><?= $this->translate('__Estado__') ?></th>
                        </tr>
                    </thead>
                    <tbody id="bodyTareas">
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    var filaSeleccionada = -1;
    var arrTareasJSON = <?= $arrTareasJSON; ?>;

    $( document ).ready(function() {
        dibujarTablaTareas();
    });

    function dibujarTablaTareas(){
        $('#bodyTareas').find('tr').remove();
    
        for (var i = 0; i < arrTareasJSON.length; i++)
        {
            var tarea = arrTareasJSON[i];

            var body = document.getElementById("bodyTareas");
            var row = body.insertRow();
            row.id = i;

            var id = row.insertCell(0);
            var fecha = row.insertCell(1);
            var ordenDeCompra = row.insertCell(2);
            var solicitante = row.insertCell(3);
            var ejecutor = row.insertCell(4);
            var planificacion = row.insertCell(5);
            var estado = row.insertCell(6);

            id.innerHTML = tarea.id;
            fecha.innerHTML = tarea.fechaSolicitud;

            if (tarea.ordenDeCompra.hasOwnProperty('id')){
                //Por el momento el numero de la orden de compra va a ser el ID
                ordenDeCompra.innerHTML = tarea.ordenDeCompra.id;
            }

            solicitante.innerHTML = tarea.solicitante.nombre + ', ' + tarea.solicitante.apellido;

            if (tarea.ejecutor.hasOwnProperty('id')){
                ejecutor.innerHTML = tarea.ejecutor.nombre + ', ' + tarea.ejecutor.apellido;
            }

            if (tarea.tipoPlanificacion.hasOwnProperty('id')){
                planificacion.innerHTML = tarea.tipoPlanificacion.descripcion;
            }

            estado.innerHTML = tarea.estadoTarea.descripcion;
        }
    }

    $(function() {
        $('#tablaTareas').on('click', 'tbody tr', function(event) {
            if (!$(this).hasClass('highlight')){
                $('.highlight').removeClass('highlight');

                $(this).addClass('highlight').siblings();
                filaSeleccionada = $(this)[0].id;

                cambiarVisibilidadBotones(true);
            }else{
                $(this).removeClass('highlight');
                filaSeleccionada = -1;
                cambiarVisibilidadBotones(false);
            }
        });
    });

    function preEditar(){
        if (filaSeleccionada >= 0){
            var tarea = arrTareasJSON[filaSeleccionada];

            window.location.replace(url + "/planificacion/asignar/" + tarea.id);
        }else{
            swal('Tarea no seleccionado',
                'Por favor seleccione la tarea que desea editar',
                'error');
        }
    }

  </script>