<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Nueva Acción</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="<?=$this->url("abm/entidad",["entidad" => "accion", "action" => "alta"])?>" name="formAltaAccion" onsubmit="preSubmit()">
                    <div class="row">
                        <div class="col-md-3">
                            <label for="nombreAccion"><span class="obligatorio">(*) </span>Nombre:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="nombreAccion" name="nombreAccion" class="form-control" required="true">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="tituloAccion"><span class="obligatorio">(*) </span>Titulo:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="tituloAccion" name="tituloAccion" class="form-control" required="true">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="iconoAccion">Icono:</label>
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="iconoAccion" name="iconoAccion" class="form-control">
                        </div>
                    </div>
                    <div class="row">
                        <input type="hidden" name="JsonData" id="JsonData">
                        <a href="<?=$this->url("abm/entidad",["entidad" => "acciones", "action" => "listar"])?>">
                            <div class="btn">Cancelar</div>
                        </a>
                        <button type="submit">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script>
function FormAltaAccionToJson(){
    var formData = {
        nombre: $('#nombreAccion').val(), 
        titulo: $('#tituloAccion').val(), 
        icono: $('#iconoAccion').val()
    };
    
    var JsonData = JSON.stringify(formData);
    
    return JsonData;
}

function preSubmit(){
    var JsonData = FormAltaAccionToJson();
    $('#JsonData').val(JsonData);

    if ($("#formAltaAccion")[0].checkValidity()){
        $("#formAltaAccion").submit();
    }else{
        $("#formAltaAccion")[0].reportValidity();
    }
}
</script>