<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("abm/entidad",["entidad" => "operaciones", "action" => "alta"])?>">Nueva Operación</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Operaciones</h3>
            </div>
            <div class="panel-body">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Titulo</th>
                            <th>Icono</th>
                            <th>Grupo</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrEntidades as $Operacion) : ?>
                        <tr>
                            <td><?= $Operacion->getNombre() ?></td>
                            <td><?= $Operacion->getTitulo() ?></td>
                            <td><?= $Operacion->getIcono() ?></td>
                            <td><?= ($Operacion->getGrupo()) ? $Operacion->getGrupo()->getTitulo() : '' ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>