<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("abm/entidad",["entidad" => "perfil", "action" => "alta"])?>">Nuevo Perfil</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Perfiles</h3>
            </div>
            <div class="panel-body">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripcion</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrEntidades as $Perfil) : ?>
                        <tr>
                            <td><?= $Perfil->getNombre() ?></td>
                            <td><?= $Perfil->getDescripcion() ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>