<div class="form-row">
    <div class="col-md-3">
        <a href="<?=$this->url("abm/entidad",["entidad" => "usuarios", "action" => "alta"])?>">Nuevo Usuario</a>
    </div>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Listado de Usuarios</h3>
            </div>
            <div class="panel-body">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre de Usuario</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Email</th>
                            <th>Bloqueado</th>
                            <th class="text-right">Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="">
                    <?php foreach($arrEntidades as $Usuario) : ?>
                        <tr>
                            <td><?= $Perfil->getNombreUsuario() ?></td>
                            <td><?= $Perfil->getNombre() ?></td>
                            <td><?= $Perfil->getApellido() ?></td>
                            <td><?= $Perfil->getEmail() ?></td>
                            <td><?= $Perfil->getBloqueado() ?></td>
                            <td></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>