<?php
    $name = $smtp_options['name'];
    $host = $smtp_options['host'];
    $port = $smtp_options['port'];
    $ssl = $smtp_options['connection_config']['ssl'];
    $username = $smtp_options['connection_config']['username'];
    $password = $smtp_options['connection_config']['password'];
?>
<div class="form-row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('__Prueba_de_Envios_de_Emails__') ?></h3>
            </div>
            <div class="panel-body mt-5">
                <div class="form-row">
                    <form id="formPruebaEmail" name="formPruebaEmail" method="post">
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>Name:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="name" class="form-control" value="<?php echo($name); ?>">        
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>Host:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="host" class="form-control" value="<?php echo($host); ?>">      
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label><?= $this->translate('__Puerto__') ?>:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="port" class="form-control" value="<?php echo($port); ?>">      
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>SSL:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="ssl" class="form-control" value="<?php echo($ssl); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>Username:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="username" class="form-control" value="<?php echo($username); ?>">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>Password:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="password" class="form-control" value="<?php echo($password); ?>">   
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>From:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="mailfrom" class="form-control" value="support@cedna.com.ar" size="100">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-2">
                                        <label>To:</label>
                                    </div>
                                    <div class="col-md-8">
                                        <input name="mailto" class="form-control" value="mariano.andres.martinez@gmail.com" size="100">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-1">
                                <label>Subject:</label>
                            </div>
                            <div class="col-md-10">
                                <input name="mailsubject" class="form-control" value="CEDNA - Pueba de Email" size="100">
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-1">
                                <label>Body:</label>
                            </div>
                            <div class="col-md-10">
                                <input name="mailbody" class="form-control" value="Este es un correo de prueba" size="100">
                            </div>
                        </div>
                        <div class="form-row mt-3">
                            <div class="col-md-2 offset-10">
                                <button class="btn btn-primary"><?= $this->translate('__Enviar__') ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    
  </script>