<?php

$url = $this->serverUrl();

// This is for the "url" catch
echo ('<script>' . PHP_EOL);
echo ('  var url = "' . $url . '";' . PHP_EOL);
echo ('</script>' . PHP_EOL);
?>

<div class="container margin-top-15">
    <div class="col-lg-3">
        
    </div>
    <div class="col-lg-6">
        <div class="card border-panel-gestion">
            <div class="card-body">
                <div class="form-row">
                    <div class="col-lg-5">

                    </div>
                    <div class="col-lg-6">
                        <i class="far fa-check-circle fa-5x" style="color : #4ddf26;"></i>
                    </div>
                </div>
                <div class="form-row">
                    <h2>Usuario creado correctamente</h2>
                </div>
                <div class="form-row">
                    <label>Para acceder a GIRO(Gestión Integral de Residuos peligrososy Otros) haga click </label> 
                    <a href="../">aquí</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        
    </div>

</div>      



